### ISSUE TITLE
Current build system doesn't allow external dependencies

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#1]
Right now everything is checked out and built by SVN, but I have Boost (for example) installed in my system. Allowing the use of external dependencies would be good.

Maybe a simple file exporting variables for which external dependencies to checkout and build would be a start? Of course it wouldn't do any detecting, but it'd allow us to manually set it up to use our system's stuff.

**Comment by lodle** [comment]
Yeah the current system is designed to be standalone (copies the boost so's to the lib dir) and uses a specific version of boost.

**Comment by Jookia** [comment]
I guessed that, but changing that someday would be a good idea as it'd cut down on build times and avoid dependency hell, it'd also integrate in to the whole shared libraries feel of Linux distros.

**Comment by lodle** [comment]
Agreed

**Comment by Jookia** [comment]
This would also help avert the GIGANTIC SVN checkout.

**Comment by admiral0** [comment]
why not cmake (no py deps any more)?

**Comment by Jookia** [comment]
Again, we have the problem of pulling in external dependencies which I don't think CMake is feeling up to yet.

**Comment by admiral0** [comment]
You can always invoke scripts in cmake and do custom macros. A solution would be to search for libs in the system and falling back to building them.

**Comment by Protektor-Desura** [comment]
You would have to build in the fallback download in the client install as well. When the client installs for the first time it would have to check for the needed libraries and download them if they aren't present. There is code to do this for games but not the client itself.

**Comment by naryl** [comment]
Build system never downloads dependencies. It's purpose is solely to make package writers' job easier and they have their own ways of dealing with dependencies.

**Comment by Jookia** [comment]
The biggest problem isn't that there's dependencies. It's that the dependencies are patched.

**Comment by Jookia** [comment]
Karolherbst's CMake additions have fixed this.
