### ISSUE TITLE
Use system-wide dependencies, instead of pulling and building them

### ISSUE THREAD

**Issue by WhyNotHugo** [desura/Desurium#100]
The current build system pulls several other repositories (I've noticed boost, breakpad, wxwidgets, and a few more).
The build mechanism should, by default, attempt to use the system-wide version (the version locally installed already).

It takes a pretty long while for all these to download and build on my test system (about an ninety minutes), and there's little point in downloading thing that are already built locally (such as the ones I mentiones above).

I belive the solution would be:
- Add these to install_depends.sh
- Include the current fetching+building scripts, but as an _alternative_ to the system-wide versions

**Comment by Jookia** [comment]
This is one of the first issues, and fixed in Karol's CMake fork. It is yet to be merged due to Windows support.

**Comment by WhyNotHugo** [comment]
Oh, my bad, sorry about the noise, I failed to find it during a quick search. Thanks!
