### ISSUE TITLE
Make finding cd keys easier

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#102]
So i read up and finally found a link to the pages with cd keys - it's under the shopping part of the sitemap on desura.com, not very friendly.

Honestly i think it needs to be an option on it's own on the application itself even if it just sends you to that page i think it needs to be made more prominent.

The Project Zomboid blog mentions you are supposed to be able to right click on a game and have an option to view cd key...i don't have this option?

**Comment by Jookia** [comment]
Already done.
