### ISSUE TITLE
cmake: build on windows

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#106]
few things:

utilcore
executables
install paths.

**Comment by karolherbst** [comment]
so one target to go: utilcore

http://pastebin.com/xVfK7bh7
http://pastebin.com/sUhKkwqY

sorry for german, but it should be clear what the error is

**Comment by karolherbst** [comment]
a little update: there are only 29 symbols to go. It seems that there is a little issue in the built wxWidgets library.

"UninstallDesuraForm.cpp.obj : error LNK2001: Nicht aufgelöstes externes Symbol ""public: static unsigned int const wxString::npos" (?npos@wxString@@2IB)"."

**Comment by karolherbst** [comment]
a little update:
http://pastebin.com/1iT7mr1q

**Comment by lodle** [comment]
This is totally borked atm.

Desura (the exe) needs to be compiled with static runtime that also means every thing it links against needs to be as well. Also debug shouldnt be a separate generation mode for Windows but cant see a way to link the third party libs debug version to debug windows

**Comment by Jookia** [comment]
Thanks to #80 I need to make it so the env CEF_DATA_PATH is set on startup to UTIL::OS::getDataPath(). I also need to implement the UTIL::OS::get*Path.

**Comment by yurikoles** [comment]
http://pastebin.com/LDHjPZPQ

**Comment by karolherbst** [comment]
wait a sec, I found the error

**Comment by Jookia** [comment]
yurikoles: Could you try now?

**Comment by yurikoles** [comment]
Now it says that patch for breakpad is already applied. http://pastebin.com/rVbM2FBG

**Comment by karolherbst** [comment]
a quick workaround for this is deleting the whole build dir and start again. I will create a pull request to fix this issue on Linux, but it should work on windows the same way

**Comment by yurikoles** [comment]
I guessed this but got same issue. Patch.exe from msys

**Comment by yurikoles** [comment]
I figured out how to resolve issue with patch.exe. I just added git's bin to path. Is there any module for cmake to find patch utility?

**Comment by karolherbst** [comment]
I don't know any

**Comment by yurikoles** [comment]
Can we just add patch.exe and msys.dll into the repo? They are very small.

**Comment by yurikoles** [comment]
Also there is many calls to patch.sh on Windows. For example [line 42 of BuildCEF.cmake](https://github.com/lodle/Desurium/blob/master/cmake/modules/BuildCEF.cmake#L42)

**Comment by yurikoles** [comment]
I tried to build it in minGW and it failed obviously, because of call to boost's bootstrap.bat while I was in bash.

**Comment by Jookia** [comment]
Hmm. The problem isn't that they're small, it's that they're binaries. Binaries in a repo is a bad idea.

**Comment by karolherbst** [comment]
The last weeks I am trying to port desurium to mingw.

Current status seems to be very good, but I don't know if we are able to build CEF this way. Although this could be a problem it won't, because mingw is using the normal win32 API so it will load dlls compiled by visual studio.

The only remaing thing seems to be breakpad and subprojects depending on it

```
C:\Users\win7\Documents\Desurium\build>make  --keep-going
[  1%] Built target boost
[  1%] Performing build step for 'breakpad'
c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/binarystream.cc:30:23: fatal error: arpa/inet.h: No such file or directory
compilation terminated.
make[3]: *** [src/processor/binarystream.o] Error 1
In file included from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:10:0,
                 from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/disassembler_x86.cc:30:
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/io.h:194:3: error: '_off64_t' does not name a type
In file included from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/disassembler_x86.cc:30:0:
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:35:36: error: 'useconds_t' was not declared in this scope
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:35:36: note: suggested alternative:
In file included from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/third_party/libdisasm/libdis.h:21:0,
                 from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/disassembler_x86.h:44,
                 from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/disassembler_x86.cc:27:
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/sys/types.h:84:22: note:   'libdis::useconds_t'
In file included from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/disassembler_x86.cc:30:0:
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:43:20: error: 'off32_t' has not been declared
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:44:22: error: 'off64_t' has not been declared
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:45:28: error: 'off32_t' has not been declared
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:46:30: error: 'off64_t' has not been declared
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/unistd.h:48:38: error: 'off32_t' has not been declared
make[3]: *** [src/processor/disassembler_x86.o] Error 1
c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/minidump.cc:49:17: error: conflicting declaration 'typedef SSIZE_T ssize_t'
In file included from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/wchar.h:9:0,
                 from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/c++/4.7.0/cwchar:46,
                 from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/c++/4.7.0/bits/postypes.h:42,
                 from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/c++/4.7.0/iosfwd:42,
                 from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/c++/4.7.0/ios:39,
                 from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/c++/4.7.0/ostream:40,
                 from c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/c++/4.7.0/iostream:40,
                 from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/google_breakpad/processor/minidump.h:86,
                 from c:/Users/win7/Documents/Desurium/build/breakpad-prefix/src/breakpad/src/processor/minidump.cc:39:
c:\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/include/_mingw.h:398:13: error: 'ssize_t' has a previous declaration as 'typedef int ssize_t'
make[3]: *** [src/processor/minidump.o] Error 1
make[3]: Target `all' not remade because of errors.
make[2]: *** [breakpad-prefix/src/breakpad-stamp/breakpad-build] Error 2
make[2]: Target `CMakeFiles/breakpad.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/breakpad.dir/all] Error 2
[  3%] Built target curl
[  5%] Built target fetch_cef
[  7%] Built target v8
[  9%] Built target wxWidget-2-9
[ 11%] Built target bzip2
[ 12%] Built target tinyxml
[ 12%] Built target sqlite
[ 13%] Built target sqlite3x
[ 17%] Built target util
[ 17%] Built target gcJSBase
[ 20%] Built target managers
[ 20%] Built target managers_window
[ 21%] Built target threads
[ 22%] Built target ipc_pipe
[ 23%] Built target util_fs
[ 24%] Built target scriptengine
[ 25%] Built target umcf
[ 25%] Built target util_web
[ 26%] Built target util_bootloader
[ 34%] Built target wx_controls
[ 34%] Built target crashuploader
[ 39%] Built target mcfcore
[ 44%] Built target servicecore
[ 45%] Built target scriptcore
[ 46%] Built target webcore
[ 64%] Built target usercore
[ 90%] Built target uicore
[ 95%] Built target utilcore
[ 95%] Built target mfc_upload_cli
[ 95%] Built target mcf_extract
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `default_target' not remade because of errors.
```

**Comment by karolherbst** [comment]
the last problem I have is, that the desura binary is written against MFC. But Mingw does not support MFC. So I would write a new "bootloader" for mingw.

In General we are not using MFC deeply, but in the bootloader, which result in round about 10 to 20 errors.

**Comment by karolherbst** [comment]
no surprise, but:

```
C:\Users\win7\Documents\Desurium\build>make test
Running tests...
Test project C:/Users/win7/Documents/Desurium/build
    Start 1: gcBuff_test
1/7 Test #1: gcBuff_test ......................   Passed    0.03 sec
    Start 2: MD5_test
2/7 Test #2: MD5_test .........................   Passed    0.02 sec
    Start 3: util_fs_copyFile
3/7 Test #3: util_fs_copyFile .................   Passed    0.05 sec
    Start 4: util_fs_copyFolder
4/7 Test #4: util_fs_copyFolder ...............   Passed    0.09 sec
    Start 5: util_fs_getAllFiles
5/7 Test #5: util_fs_getAllFiles ..............   Passed    0.05 sec
    Start 6: util_fs_getAllFolders
6/7 Test #6: util_fs_getAllFolders ............   Passed    0.05 sec
    Start 7: util_string_sanitizeFilePath
7/7 Test #7: util_string_sanitizeFilePath .....   Passed    0.03 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =   0.98 sec
```

**Comment by karolherbst** [comment]
now I have a running client, but without cmd options and stuff like that. I will rebase everything tomorrow and create some pull request for non mingw related stuff I need.

**Comment by karolherbst** [comment]
![3.png](https://f.cloud.github.com/assets/171766/2163/69fbce60-41a5-11e2-8aeb-57e2eef625ba.png)

here, this is nice

**Comment by karolherbst** [comment]
okay, seems to hang after login. I have to investigate further

**Comment by karolherbst** [comment]
okay found it: https://github.com/karolherbst/Desurium/blob/mingw/src/executable/bootloader_win/code/DesuraMainMingw.cpp#L70

**Comment by PiotrMi** [comment]
C:\Users\Adam Wankowski\Documents\GitHub\Desurium>IF NOT EXIST build (mkdir buil
d )

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>cd build

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>cmake .. -DCMAKE_INSTALL
_PREFIX=../install -G "NMake Makefiles"
WW building Desura without c-ares is not supported.
WW Make sure, that your system installed cURL has ares support.
WW Ignore this if you are aware of what you do. See #189 for further information
.
-- detected 32bit
-- Could NOT find Boost
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Optional package Sqlite3 was not found
-- Could NOT find TINYXML (missing:  TINYXML_LIB TINYXML_H_PATH)
tinyxml >= 2.6 is required. Using builtin
-- Could NOT find v8 (missing:  V8_INCLUDE_DIR V8_LIBRARIES)
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) (Required is at least ve
rsion "2.9")
CMake Error at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindPack
ageHandleStandardArgs.cmake:97 (message):
  Could NOT find Patch (missing: PATCH_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindPackageHandleStan
dardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPatch.cmake:16 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:190 (find_package)

-- Configuring incomplete, errors occurred!

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>nmake

Microsoft (R) Program Maintenance Utility, Version 10.00.30319.01
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

NMAKE : fatal error U1064: MAKEFILE nicht gefunden und kein Ziel angegeben
Stop.

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>

using Git and Visual Studio 10 Command Prompt. Any suggestions?

**Comment by karolherbst** [comment]
"Could NOT find Patch (missing: PATCH_EXECUTABLE)"

patch.exe has to be in the current PATH variable, because we need it in various cmake steps. You could also helping us improving our FindPatch Module: https://github.com/lodle/Desurium/blob/master/cmake/modules/FindPatch.cmake

**Comment by PiotrMi** [comment]
I managed to solve the patch.exe problem but now something else isn´t working:

Setting environment for using Microsoft Visual Studio 2010 x86 tools.

h:\Program Files (x86)\Microsoft Visual Studio 10.0\VC>c:

C:>cd C:\Users\Adam Wankowski\Documents\GitHub\Desurium

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>build_desura.bat

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>IF NOT EXIST build (mkdir buil
d )

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>cd build

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>cmake .. -DCMAKE_INSTALL
_PREFIX=../install -G "NMake Makefiles"
WW building Desura without c-ares is not supported.
WW Make sure, that your system installed cURL has ares support.
WW Ignore this if you are aware of what you do. See #189 for further information
.
-- detected 32bit
-- Could NOT find Boost
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Optional package Sqlite3 was not found
-- Could NOT find TINYXML (missing:  TINYXML_LIB TINYXML_H_PATH)
tinyxml >= 2.6 is required. Using builtin
-- Could NOT find v8 (missing:  V8_INCLUDE_DIR V8_LIBRARIES)
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) (Required is at least ve
rsion "2.9")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Adam Wankowski/Documents/GitHub/De
surium/build

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>nmake

Microsoft (R) Program Maintenance Utility, Version 10.00.30319.01
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

[  1%] Built target boost
[  1%] Performing download step (download, verify and extract) for 'breakpad'
-- downloading...
     src='https://github.com/downloads/lodle/Desurium/breakpad-850.tar.gz'
     dst='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-prefi
x/src/breakpad-850.tar.gz'
     timeout='none'
-- downloading... done
-- verifying file...
     file='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-pref
ix/src/breakpad-850.tar.gz'
-- verifying file... done
-- extracting...
     src='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-prefi
x/src/breakpad-850.tar.gz'
     dst='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-prefi
x/src/breakpad'
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_header(): Can't create '\'
CMake Error: Current file:breakpad/autotools/compile
CMake Error: Problem extracting tar: C:/Users/Adam Wankowski/Documents/GitHub/De
surium/build/breakpad-prefix/src/breakpad-850.tar.gz
-- extracting... [error clean up]
CMake Error at breakpad-stamp/extract-breakpad.cmake:33 (message):
  error: extract of 'C:/Users/Adam
  Wankowski/Documents/GitHub/Desurium/build/breakpad-prefix/src/breakpad-850.tar
.gz'
  failed

NMAKE : fatal error U1077: "echo": Rückgabe-Code "0x1"
Stop.
NMAKE : fatal error U1077: ""h:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\nmake.exe"": Rückgabe-Code "0x2"
Stop.
NMAKE : fatal error U1077: ""h:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\nmake.exe"": Rückgabe-Code "0x2"
Stop.

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>

**Comment by karolherbst** [comment]
the archives uploaded to github are a bit broken for windows.

downloads can be found here:
https://github.com/lodle/Desurium/downloads

but we have another problem with that: https://github.com/blog/1302-goodbye-uploads

**Comment by PiotrMi** [comment]
Couldn´t we just include these archives in the repository?

2013/3/29, Karol Herbst notifications@github.com:

**Comment by karolherbst** [comment]
I wouldn't to that. The easiest thing would be to just download the packages and pass them via cmake: https://github.com/lodle/Desurium/blob/master/CMakeLists.txt#L20

At the time I created the archives I couldn't imagine, that these archives can't be read by windows. For development (much later) I've converted them locally and passed the location via cmake (-DBREAKPAD_URL="C:\path")

**Comment by PiotrMi** [comment]
I downloaded the packages as you said but I´m not sure what to do now. I extracted them into their folders and even left the not extracted archives there. I don´t really know what I should do. 

Setting environment for using Microsoft Visual Studio 2010 x86 tools.

h:\Program Files (x86)\Microsoft Visual Studio 10.0\VC>c:

C:>cd C:\Users\Adam Wankowski\Documents\GitHub\Desurium

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>build_desura.bat

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>IF NOT EXIST build (mkdir buil
d )

C:\Users\Adam Wankowski\Documents\GitHub\Desurium>cd build

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>cmake .. -DCMAKE_INSTALL
_PREFIX=../install -G "NMake Makefiles"
WW building Desura without c-ares is not supported.
WW Make sure, that your system installed cURL has ares support.
WW Ignore this if you are aware of what you do. See #189 for further information
.
-- detected 32bit
-- Could NOT find Boost
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Optional package Sqlite3 was not found
-- Could NOT find TINYXML (missing:  TINYXML_LIB TINYXML_H_PATH)
tinyxml >= 2.6 is required. Using builtin
-- Could NOT find v8 (missing:  V8_INCLUDE_DIR V8_LIBRARIES)
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) (Required is at least ve
rsion "2.9")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Adam Wankowski/Documents/GitHub/De
surium/build

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>nmake

Microsoft (R) Program Maintenance Utility, Version 10.00.30319.01
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

[  1%] Built target boost
[  1%] Performing download step (download, verify and extract) for 'breakpad'
-- downloading...
     src='https://github.com/downloads/lodle/Desurium/breakpad-850.tar.gz'
     dst='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-prefi
x/src/breakpad-850.tar.gz'
     timeout='none'
-- downloading... done
-- verifying file...
     file='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-pref
ix/src/breakpad-850.tar.gz'
-- verifying file... done
-- extracting...
     src='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-prefi
x/src/breakpad-850.tar.gz'
     dst='C:/Users/Adam Wankowski/Documents/GitHub/Desurium/build/breakpad-prefi
x/src/breakpad'
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_header(): Can't create '\'
CMake Error: Current file:breakpad/autotools/compile
CMake Error: Problem extracting tar: C:/Users/Adam Wankowski/Documents/GitHub/De
surium/build/breakpad-prefix/src/breakpad-850.tar.gz
-- extracting... [error clean up]
CMake Error at breakpad-stamp/extract-breakpad.cmake:33 (message):
  error: extract of 'C:/Users/Adam
  Wankowski/Documents/GitHub/Desurium/build/breakpad-prefix/src/breakpad-850.tar
.gz'
  failed

NMAKE : fatal error U1077: "echo": Rückgabe-Code "0x1"
Stop.
NMAKE : fatal error U1077: ""h:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\nmake.exe"": Rückgabe-Code "0x2"
Stop.
NMAKE : fatal error U1077: ""h:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\nmake.exe"": Rückgabe-Code "0x2"
Stop.

C:\Users\Adam Wankowski\Documents\GitHub\Desurium\build>

**Comment by karolherbst** [comment]
I worked on that on my branch win32-breakpad. It compiles (cef is throwing some errors, wich can be fixed by hand) and runs. Installing games does not work and I have to change some path handling.

**Comment by karolherbst** [comment]
here I've packaged the desurium binaries. Visual Studio 2010 redist. packages are needed to run it.

desurium:
https://dl.dropboxusercontent.com/u/19446730/desurium_win32-breakpad-karolherbst-52890d2.zip

vc 2010:
https://www.microsoft.com/de-de/download/details.aspx?id=5555
