### ISSUE TITLE
CEF is awesome, big and depends on own build system

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#107]
At the moment I try to build CEF and cougette with cmake, but this is not so easy as I thought. My idea is to invoke the known cef_create_projects script via cmake to get everything build.
It seems that cef and courgette were the main reasons to choose gyp.

Jookia:
I say we worry about CEF last. I think your idea is as correct as it can be. Check out via CMake, yadayadayada, build it using gyp. Please note that gyp requires Python 2.

for reference the tree with old build files:
https://github.com/lodle/Desurium/tree/c21c857ac21957e1785aa60cac9439e8dc3f2ab6

ebuild in gentoo to build chromium:
http://gentoo-overlays.zugaina.org/gentoo/portage/www-client/chromium/chromium-18.0.1025.142.ebuild

**Comment by karolherbst** [comment]
I've added a link to a gentoo ebuild for reference

**Comment by Jookia** [comment]
You actually got Cef to build. Wow.
