### ISSUE TITLE
Crypto causes almost everything to fail

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#11]
[As you can see here in this gist](https://gist.github.com/056295da80f5db01ea82), a single error in crypto is breaking almost everything.

```
src/third_party/crypto/include/secblock.h:32:7: note: void CryptoPP::AllocatorBase<T>::construct(CryptoPP::AllocatorBase<T>::pointer, const T&) [with T = CryptoPP::HuffmanDecoder::LookupEntry, CryptoPP::AllocatorBase<T>::pointer = CryptoPP::HuffmanDecoder::LookupEntry*]
src/third_party/crypto/include/secblock.h:32:7: note: candidate expects 2 arguments, 1 provided
```

**Comment by lodle** [comment]
Try applying the patch in the thrid_party/patches folder

**Comment by Jookia** [comment]
That fixed one error, I then had to enable some code. I still have at least another error to fix before this thing will compile.

**Comment by Jookia** [comment]
Turns out the patch didn't fix anything and only made me have to re-enable some code disabled by the patch, back to square one.

**Comment by Jookia** [comment]
[Okay, this turns out to be a GCC 4.6 C++0x bug.](https://code.google.com/p/owasp-esapi-cplusplus/issues/detail?id=11)

I'm going to roll out a patch to my fork shortly.
