### ISSUE TITLE
Failed to select value for key

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#110]
cmake build - console output:
(24988, son of 24987) /home/karol/Dokumente/repos/Desurium/src/static/util/code/UtilLinux.cpp:349 - Failed to select value for key "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\Desura": "nothing to read"!

**Comment by lodle** [comment]
Looks like its trying to find the windows registry bindings to the URI desura://. Might be worth tracing where that is coming from

**Comment by Jookia** [comment]
Fixed in a1c06449e7e64234b4aadc3afa9ae9674c27f859
