### ISSUE TITLE
install-deps problem

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#114]
Okay so now i see cmake is around it should be easier to compile but the deps installer doesn't work with ubuntu 12.04;

liam@liam-desktop:~/Downloads/lodle-Desurium-4669625$ sudo '/home/liam/Downloads/lodle-Desurium-4669625/install-deps.sh' 
Package `libv8-dev' is not installed and no info is available.
Package`libc-ares-dev' is not installed and no info is available.
Package `libboost-dev' is not installed and no info is available.
Package`libboost-date-time-dev' is not installed and no info is available.
Package `libboost-filesystem-dev' is not installed and no info is available.
Package`libboost-system-dev' is not installed and no info is available.
Package `libboost-thread-dev' is not installed and no info is available.
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
everything intalled

It doesn't find the packages...and tells me everythings installed

**Comment by karolherbst** [comment]
the script is a little bit hacky for debian/ubuntu, because I don't know a good way to check if something is installed with apt in bash.

The script worked fine on my debian machine. I will take a look, when I'm home.

**Comment by Jookia** [comment]
Those apostrophes look bad.

**Comment by ssokolow** [comment]
You could do something like this:

```
DEPS="gcc git-core subversion m4 build-essential binutils automake autoconf libtool libgtk2.0-dev libnss3-dev libgconf2-dev libgnome-keyring-dev libdbus-glib-1-dev gperf bison libcups2-dev flex libasound2-dev libbz2-dev libxpm-dev libx11-dev libssl-dev libnotify-dev scons libv8-dev libc-ares-dev libboost-dev libboost-date-time-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev"
for dep in $DEPS; do
    if `dpkg -s "$dep" 1>/dev/null 2>&1` ; then
        echo "$dep installed"
    else
        aptitude install "$dep"
    fi
done
```

The `whoami` test is also acting as if "ssokolow" and "root" are the same thing on my system, so here's a solution for that (which also gives the exact command to type):

```
if [ "$(id -u)" != "0" ]; then
    echo "Run this as root! `tput bold`sudo $0`tput sgr0` should do the trick."
    exit
fi
```

Oh, and if someone with edit privs wants to fix the initial post, just indent the shell snippet by four characters and, if memory serves, GitHub code formatting should override the special meaning of the backticks in it.

EDIT: Whoops. It's getting late. Late nights and coding don't mix. Fixed.

**Comment by Jookia** [comment]
Is it fixed now?

**Comment by ssokolow** [comment]
I'm still on 11.10 and all my deps are installed already, so I'll leave it up to @liamdawe to check... unless he never does. In which case, I'll take the 30 minutes or so to set up a VirtualBox VM and test it myself.

**Comment by LiamDawe** [comment]
Sorry forgot all about this issue, i don't actually have an 11.10 machine to test now.
