### ISSUE TITLE
Replace install-deps.sh with distro package sources?

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#117]
This would benefit greatly, as we'd have dependency checking, and also a way to install. Right now we have one for Gentoo, which is a start.

Links:

https://bugs.gentoo.org/show_bug.cgi?id=395837
https://github.com/lodle/Desurium/blob/master/gentoo/portage/games-util/desura/desura-9999.ebuild

**Comment by Jookia** [comment]
Quick note: I'm not trying to imply we maintain all distros package sources, just ones that aren't maintained by package maintainers.

**Comment by karolherbst** [comment]
I would like to apply for being a maintainer for the gentoo ebuilds. Does anyone have something against it?

**Comment by Jookia** [comment]
karolherbst 2012

**Comment by karolherbst** [comment]
I think we can close this, because distributions will hold their own files. Further we have one a PKGBUILD and an ebuild.

And we have also support for essential (binary- and sourcepackage creation.
