### ISSUE TITLE
Config menu for cvars

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#118]
As noted in #89, auto updating being on by default and only changeable by a cvar is very inconvenient, but on purpose. To avoid ... less savy ... people from accidently breaking things and complaining to DesuraNET.

Now, Firefox and Windows and anything you've ever seen with a registry has advanced options hidden away in such a way that you won't go changing things unless you have a death wish.

Unfortunately, editing the cvars without the debug console is next to impossible. They're stored in an SQLite database. Even I'd screw up editing that.

In IRC it's been discussed and concluded that we have something like Firefox's about:config, to edit individual cvars. This means it can all be done inside the application, which is more convenient than finding configuration files. Since Desurium lacks an address bar however, I propose the method of which you access it is to type 'i am hardcore' in to the search bar. Of course the downside of this is that you wouldn't be able to search for 'i am hardcore'.

**Comment by Protektor-Desura** [comment]
You could also do something like access::advanced. No chance you can type that by accident and no game will ever have that.

**Comment by Jookia** [comment]
Yes, but I worry that a bunch of smartass users are going to change their names or have a group with the name of it.

**Comment by ssokolow** [comment]
I can think of two solutions to that:
1. At least on Linux, release Desura builds _do_ have a console window with a text-entry field. You could require that a command be typed in there to pull up the cvar config menu.
2. You could require Desura be launched with a command-line flag like `desura --edit-cvars`. (My main concern there is that it could be an even bigger barrier to entry than intended for non-Linux users)

**Comment by Protektor-Desura** [comment]
The Windows version of the client also has a console window that can be brought up. Moving it to a console command would work for both platforms and be the least confusing and less likely to be accidentally clicked by a user who has no idea what they are doing. 

I like the idea of making it a console command.

**Comment by Jookia** [comment]
Isn't the console debug only though?

**Comment by ssokolow** [comment]
I've got the console in the pre-GPL official build I keep in `~/opt/desura` so I suspect not.

**Comment by Jookia** [comment]
Well if somebody told me that the console was in release too, I'd of been happy to just use that. In fact, that's kind of what cvars are for.

**Comment by Protektor-Desura** [comment]
The console is in the standard release versions. I am still using the default clients and it exists in both the Windows and Linux versions. It is not limited to debug versions.

**Comment by Jookia** [comment]
Okay, so just use the console.
