### ISSUE TITLE
Desurium console unreadable with oxygen-gtk

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#127]
I have a Problem regarding the desurium konsole. it has some kind of gray layer on top of it and is therefore unreadable. I have no specific output for that will check later again.

**Comment by Jookia** [comment]
Could you post a screenshot?

**Comment by TheSiege** [comment]
http://img404.imageshack.us/img404/5113/desuriumconsole1.png
http://img140.imageshack.us/img140/2104/desuriumconsole2.png

the second one is resizing behavior

**Comment by Jookia** [comment]
What OS?

**Comment by TheSiege** [comment]
Gentoo Linux
Linux 3.2.9-rt17-rt17 #2 SMP PREEMPT RT
KDE SC 4.8.1

**Comment by Jookia** [comment]
Hmm. Do you have any non-KDE DEs installed?

**Comment by TheSiege** [comment]
well, yes it works with twm but this is not a viable alternative.

**Comment by Jookia** [comment]
Is this due to compositing?

**Comment by TheSiege** [comment]
I have tried composite type opengl and xrender still the same

**Comment by Jookia** [comment]
But if you turn the compositing off does it look the same?

**Comment by karolherbst** [comment]
I have this issue, too. Same behavior when without compositing.

**Comment by Jookia** [comment]
So is this KDE specific?

**Comment by karolherbst** [comment]
with Xfce I didn't have this issue, so I think so.

**Comment by karolherbst** [comment]
I found the problem:

This bug appears, while using the oxygen-gtk theme. Because I have other problems with this theme (codeblocks cannot start) I would recommend commit a bug report to KDE because of this.

**Comment by Jookia** [comment]
This is a KDE bug. If one of you can file a bug report off to the folks at KDE, I'll be happy to close this bug.

**Comment by Jookia** [comment]
Is this specific to Oxygen-GTK or any GTK related theme in KDE?

**Comment by karolherbst** [comment]
only oxygen-gtk

**Comment by Jookia** [comment]
Could you send a bug report upstream please?

**Comment by karolherbst** [comment]
I'll do it when I'm home, because I need a screenshot for this

**Comment by Jookia** [comment]
Allegedly fixed in #167.
