### ISSUE TITLE
Missing bin/bittest

### ISSUE THREAD

**Issue by Telemaniaka** [desura/Desurium#129]
Tried to run a 32bit game on my 64bit Ubuntu and it said I don't have 32bit libraries. Which I have. I noticed in the console that it said that `bin/bittest` was missing. After copying it from the official release the game started correctly.

**Comment by Jookia** [comment]
In [this file](https://github.com/lodle/Desurium/blob/master/src/shared/usercore/code/ItemHandle_nix.cpp#L125) we have this. So maybe it'd be better to reimplement it?

```
#ifdef NIX64
    if (!useXdgOpen && branch && branch->is32Bit())
    {
        int testRet = system("bin/bittest");

        if (testRet != 0)
            throw gcException(ERR_NO32LIBS);
    }
#endif
```

I'm guessing binttest is a 32bit executable, and it's testing to see if it's able to run it.

**Comment by Jookia** [comment]
Okay, I've implemented bittest. Would you mind trying to recreate the bug in the latest source code?

**Comment by Telemaniaka** [comment]
I got it working but had to make a few changes:
1. I had to install the `gcc-multilib` package to compile the 32bit desura_bittest on the 64bit Ubuntu (this could be just me not knowing how to prepare a dev environment but it would be nice if it could be included in `install-debs.sh`)
2. Desura couldn't find `desura_bittest`. It got fixed after changing `system("desura_bittest")` to `system("bin/desura_bittest")`
3. It still told me I don't have 32 bit libraries. I noticed that the `desura_bittest` source said `return 1` while the check in Desura is 
   
   <pre>
   if (testRet != 0) 
           throw gcException(ERR_NO32LIBS);
   </pre>

**Comment by Jookia** [comment]
1 and 3 are valid points, 2 is odd as run_desura.sh should put it in the PATH, much like a typical install would. Are you doing that?

Maybe we need CMake to check if it can compile the bittest.

**Comment by Jookia** [comment]
Turns out I was wrong about 2. Anyway, working on a fix.

**Comment by Jookia** [comment]
Does 8288cd9c12581322d524090ed248a741e174e1aa fix things?

**Comment by Telemaniaka** [comment]
Yes, it's working now.
