### ISSUE TITLE
Settings menu is broken.

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#152]
This broke a while back, I'm not sure which commit.

**Comment by lodle** [comment]
There are a few files that get renamed for lin and win, there is a tool that auto does this, should run that instead of doing the manual copy

**Comment by Jookia** [comment]
Oh, so that's what process data folder does? I guess we can remove it then if we can do the job in CMake?

**Comment by lodle** [comment]
well as long as cmake does it recursively and removes the opposite files (i.e. _win files on _lin)
