### ISSUE TITLE
build_make_clean.sh expects /bin/sh to be bash

### ISSUE THREAD

**Issue by ssokolow** [desura/Desurium#154]
On Debian-based systems (Ubuntu included), `/bin/sh` is a symlink to a lightweight Bourne shell named dash rather than a symlink to `/bin/bash`.

This causes `build_make_clean.sh` to report a syntax error because `[[ TEST ]]` is a bash-specific syntax extension.

**Comment by Jookia** [comment]
Well that explains a lot.

**Comment by ssokolow** [comment]
I'm out of time right now, but I'll try to make this dash-compatible as soon as I can spare a moment.

**Comment by joehillen** [comment]
There's no reason not to just use bash.

**Comment by ssokolow** [comment]
@joehillen: True in theory. I think the availability of `/bin/bash` is required as part of the subset of [LSB](https://en.wikipedia.org/wiki/Linux_Standard_Base) compliance that non-RPM distros consider legitimate and worthy of default compliance.

However, you forgot one thing... When I can spare the time, figuring out the dash equivalent is something I want to do both for fun and to extend my skills.

**Comment by karolherbst** [comment]
should be fixed in e72f237af96c1589cd79efcc77bae00e5a33443a
