### ISSUE TITLE
Active region for "Home" button is counter-productively tight

### ISSUE THREAD

**Issue by ssokolow** [desura/Desurium#160]
After several confusingly-failed attempts to click the "Home" button I finally realized that the active region is literally the visible portion of the icon and nothing more and my clicks were landing in the empty region representing a front door.

Making the bounding box a square larger than the visible area (as it is with the rest of the icons on the toolbar) would be much more sensible, less confusing, and easier to click on.

What really confuses me is that the tooltip _does_ respond as would be expected... you just don't get on-hover highlight or on-click effects unless you're on a visible portion of the icon.

**Comment by Jookia** [comment]
> my clicks were landing in the empty region representing a front door.

AHAHAHAHA.

But really, I'll set this for the next milestone.

**Comment by Jookia** [comment]
Fixed.

**Comment by ssokolow** [comment]
I'd assume this will get the effect of being fixed, but if it's still using the alpha channel as a click mask, I can easily see this becoming a problem elsewhere in the GUI in the future. (If nowhere else, it's likely to pop up as a counter-intuitive bug in non-default themes)
