### ISSUE TITLE
Automatically Delete MCFs

### ISSUE THREAD

**Issue by Protektor-Desura** [desura/Desurium#162]
A toggle option to tell the client to delete MCFs after install rather than keeping them around for just in case. Some users complain and some want them saved. A toggle is the best way to make both happy. If someone turns it on accident it won't matter other than they have to re-download the game again.

**Comment by imgxx** [comment]
settings-> general-> clean up mcf's after use.
is it the same checkbox?

**Comment by Protektor-Desura** [comment]
My Bad. Yes it looks like that is exactly what it is.

**Comment by Jookia** [comment]
So we should close this?

**Comment by Protektor-Desura** [comment]
Yes
