### ISSUE TITLE
Distorted text on the compiler

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#168]
Just FYI when running build_desura the output starts as;

"liam@liam-Ideapad-Z570:~$ '/home/liam/Downloads/lodle-Desurium-b30b308/build_desura.sh' 
-e Make sure to run \e[1;31msudo install-deps.sh\e[0m before compiling!
"

I take it that's not normal.

**Comment by ssokolow** [comment]
Same problem as `build_make_clean.sh` in issue #154.

`build_desura.sh` assumes that `/bin/sh` will be a symlink to `/bin/bash` but Debian-based distros like Ubuntu use a lightweight, POSIX-compliant Bourne shell named dash (`/bin/dash`) for `/bin/sh` instead to speed up execution of shell scripts during startup.

The problem in this case is that `-e` is a bash-specific extension to the `echo` built-in. (`-n` is also not supported by dash. That's a Korn shell extension that bash picked up. zsh then picked both of them up when copying bash's echo command.)

The only portable way to do that sort of thing is to use `printf`. I have less than two minutes before I have to get busy on something, but I'll try to make time to patch this specific issue tomorrow.

**Comment by Jookia** [comment]
How about we just don't have those things.

**Comment by ssokolow** [comment]
Your choice. I chose making it work in dash because I've done that exact thing before for one of my own scripts and I tend to be stubborn about getting "the ideal choice" to work.

**Comment by lodle** [comment]
there is an option to disable color --nocolor i think it is

**Comment by lodle** [comment]
oh never mind me, looks like it got removed
