### ISSUE TITLE
Some games listed as "Not ready" after restarting the client.

### ISSUE THREAD

**Issue by sakuramboo** [desura/Desurium#177]
So far, Xonotic and Warlock's Gauntlet come up as being "Not ready" every time the client starts. When I open it, it checks if the files are there and verifies and then marks them as "Ready". Once I restart the client, both of those games become "Not ready".

**Comment by Protektor-Desura** [comment]
Fixed and should be reported to support@desura.com since this is not an issue with the client but rather the game.

**Comment by ssokolow** [comment]
@Protektor-Desura: If you don't mind satisfying my curiosity, how exactly does that work? Is it an issue with the server-side record for the game?

**Comment by Protektor-Desura** [comment]
Correct. The install information and checking to see if a game is installed comes from a server side record.

**Comment by Jookia** [comment]
Okay.
