### ISSUE TITLE
XDG_RUNTIME_DIR requires mtime to be set

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#18]
Every 5 hours or so (has to be under 6 hours), any files we put in XDG_RUNTIME_DIR (like the locks and sockets) should have their mtime attribute update to avoid being cleaned out. See [here](http://standards.freedesktop.org/basedir-spec/basedir-spec-0.7.html) for details.

**Comment by lodle** [comment]
Should add something to usercore/UpdateThread_Old.cpp to do this

**Comment by Jookia** [comment]
I was thinking of just adding a list of files to an array and running a check in the main loop if time has passed since last mtime change that's greater than 5 hours, the mtime would be updated in all the files.

I'm not that familiar with the architecture of Desurium, so how would you go about it?

**Comment by lodle** [comment]
See the file above, its a thread that does the update poll

**Comment by Jookia** [comment]
I'll work on implementing that today I guess. Mind coming on IRC?

**Comment by Jookia** [comment]
Pull request #22 fixes this.
