### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by yurikoles** [desura/Desurium#180]
cmake .. -DCMAKE_INSTALL_PREFIX=../install -G "NMake Make
files"
-- detected 32bit
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
-- Optional package Sqlite3 was not found
-- Could NOT find TinyXML (missing:  TINYXML_INCLUDE_DIR TINYXML_LIBRARIES)
-- Could NOT find v8 (missing:  V8_INCLUDE_DIR V8_LIBRARIES)
-- Found Subversion: C:/Program Files/SlikSvn/bin/svn.exe (found version "1.7.4"
)
-- Found Git: C:/Program Files (x86)/Git/cmd/git.cmd (found version "1.7.10.msys
git.1")
CMake Error at src/CMakeLists.txt:117 (add_dependencies):
  add_dependencies Adding dependency to non-existent target: desura

-- Configuring incomplete, errors occurred!

**Comment by Jookia** [comment]
Please add this to #106.

**Comment by yurikoles** [comment]
http://pastebin.com/LDHjPZPQ

**Comment by Jookia** [comment]
Please take it to #106.
