### ISSUE TITLE
get*Path is used incorrectly.

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#192]
Currently sometimes it's called with / at the start, sometimes it's not. This is breaking stuff, so instead of ~/.desura/crc, we get ~/.desuracrc .

I'm pretty sure some regex could fix this. Currently I'm thinking of something along the lines of

`find . -type f -exec sed -i "s/\(get.+Path(*\"\)\//\1/g"`

would work, as long as I got get*Path to add a slash before extra.

**Comment by lodle** [comment]
using a sledge hammer for a nail, just check for a starting slash in the function and add it if tis not there

**Comment by Jookia** [comment]
I'd rather fix the codebase than to enable bad code. Could you get on IRC if you're going to pop up at 11PM at night?

**Comment by lodle** [comment]
not tonight but ill jump on over the weekend

**Comment by Jookia** [comment]
Alrighty.

**Comment by ssokolow** [comment]
Fixing the codebase is always desirable, but it's probably also a good idea to put in some kind of guard against subtle bugs like that getting reintroduced down the line.

Maybe something that announces the mis-use on stderr and then either dies (debug builds) or silently corrects things (release builds).

**Comment by Jookia** [comment]
Fixed.
