### ISSUE TITLE
Current build instructions don't work

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#2]
Currently they don't work. The ones in the readme. If you clone this repo and then follow the instructions exactly you'll see the problem. I'm currently hacking my way through it trying to fix it but I'm not sure if it's just my problem.

**Comment by lodle** [comment]
Whats the issue?

**Comment by Jookia** [comment]
It's quite a lot of them, I'll try to summarise what I remember:

Stuff isn't executable, so you have to put 'sh' infront of it to launch it in the shell.
Checking third party stuff out assumes you're in the third_party directory, yet the readme doesn't note that so I checked everything out in to the project's root directory.
I had to modify BuildAll to use .sh and to remove the ./lin_dir as I had to run it from the lin_dir directory so the scripts would be able to do ../boost, etc.

**Comment by lodle** [comment]
Thats more of a git issue not setting the files as +x, as I copied the repo on windows. Ill fix that now.

**Comment by lodle** [comment]
Fixed in last commit

**Comment by Jookia** [comment]
Side comment, FindCurl.sh and others go up a directory, does that mean I should've checked out stuff and had my working directory as src/?
