### ISSUE TITLE
Breadcrumbs are positioned too high.

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#213]
![](http://i.imgur.com/Cl9KR.png)

I've managed to get this fixed somehow by removing the last column, specifically changing [this line](https://github.com/lodle/Desurium/blob/master/src/shared/uicore/code/HtmlToolBarControl.cpp#L72) to having 10 columns instead of 11. But that removes the last search element.

**Comment by lodle** [comment]
maybe the search element height is to big

**Comment by karolherbst** [comment]
I found out, that the whole bar is a tiny bit higher than on desura. You see a pixel line underneath your avatar.

**Comment by Jookia** [comment]
Hmm, that should be an easy fix then?

**Comment by karolherbst** [comment]
fixed in 7a4e39b717d2c3a4a0a050fd8c2fc9579c5728c9

**Comment by LiamDawe** [comment]
Hooray this was so annoying to look at!
