### ISSUE TITLE
implement notification

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#237]
I'd favor some kind of notification when ~/.desura/cache/applock is still present. Right now it just doesn't start desurium without any error at all.

**Comment by Jookia** [comment]
I'll do this but only through libnotify: I hate Firefox telling me it's not shut down.

**Comment by Jookia** [comment]
Done. 5dd2abf4c7667e2619c1dbe1029c1183791497b7

**Comment by TheSiege** [comment]
today I tried starting desurium today. and got the following console output:

```
$XDG_CONFIG_HOME not set, falling back to $HOME/.config.$XDG_CACHE_HOME not set, falling back to $HOME/.cache.
```

then nothing, no process running and nothing, starting multiple times did not help
removing ~/.desura/cache/applock makes it start again, but I have to do this manually
the message that this needs to be removed got excluded in commit f0a73405602ec7fb63e6d5b6a19c1e4ccb84f45a
from @karolherbst

**Comment by karolherbst** [comment]
this is a wxWidgets bug and should be reported there

**Comment by karolherbst** [comment]
the class is "wxSingleInstanceChecker". We have to now under which circumstances this bug occurs (did desurium crash before? and so on)

**Comment by TheSiege** [comment]
not sure if desurium crashed; when it happens, it happens when I turn the computer on; never when desurium ran, so could be related to shutdown?

**Comment by karolherbst** [comment]
it could be. Try to kill desurium with a SIGKILL signal an not with SIGTERM (what is kill and killall default signal)
