### ISSUE TITLE
small build problem

### ISSUE THREAD

**Issue by higuita** [desura/Desurium#238]
when trying to build desurium on linux , i found a small problem... if it fails for some reasons, next try might fail because of locked svn repositories:

Building CXX object src/static/managers/CMakeFiles/managers.dir/code/ThemeManager.cpp.o
-- [download 1% complete]
svn: E155004: Working copy '/home/higuita/build/Desurium/build/external/depot_tools/src/depot_tools' locked.
svn: E155004: '/home/higuita/build/Desurium/build/external/depot_tools/src/depot_tools' is already locked.
svn: run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
make[2]: **\* [external/depot_tools/src/depot_tools-stamp/depot_tools-download] Error 1
make[1]: **\* [CMakeFiles/depot_tools.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....

the removal of old checkouts or a lock test and svn cleanup might be a good ideia

**Comment by karolherbst** [comment]
For me this is more a cmake - ExternalProject bug

so it would make much more sense to report it to the cmake project

**Comment by karolherbst** [comment]
bug closed, because we don't use svn checkouts anymore
