### ISSUE TITLE
Spurious "Not compiled with 32 bit application support [76.0]" error

### ISSUE THREAD

**Issue by ssokolow** [desura/Desurium#247]
In Desurium built from fd73e307714d4111c86aad6de57f651f3e82faf2, AlterEgo (a 32-bit Mono-based game) installs without complaint (and I know the Mono detection works properly, since I initially forgot to `sudo apt-get install mono-complete`) but, once it's installed, attempts to run it give the following message:

```
The version of Desurium you're running
does not support running 32 bit games.

Not compiled with 32 bit application
support. [76.0]
```

However, this is proven to be either a lie or an overly broad check if I manually run `./desura_launch_Play.sh` inside the game's installation directory.

**Comment by Jookia** [comment]
You must enabled the CMake 32BIT_SUPPORT flag. Currently there's no
automatic detection.

On Mon, Jun 18, 2012 at 7:40 AM, Stephan Sokolow <
reply@reply.github.com

**Comment by ssokolow** [comment]
My complaint is that, when the flag is disabled, the result is very confusing since support for running 32-bit games is part of the OS, not Desura.

It'd be better to have it made more clear that what's missing is Desura's support for detecting whether 32-bit programs can run... maybe with the addition of a "this version of Desura cannot install 32-bit games" message on install.

Oh, and how would I patch `build_desura.sh` to enable that flag? (I really don't like messing around in the interactive UIs)

**Comment by Jookia** [comment]
Add -D32BIT_SUPPORT=1 to cmake arguments.

On Tue, Jun 19, 2012 at 1:44 AM, Stephan Sokolow <
reply@reply.github.com

**Comment by ssokolow** [comment]
Ugh. Building with that flag fails because 32-bit `libgcc.a` and the like aren't installed and, apparently, Ubuntu Precise's new multi-arch support isn't quite robust enough for `sudo apt-get gcc:i386` to avoid package conflicts.

I guess all I can do for now is add the apps to my system launcher and wait for you to fix things.

**Comment by karolherbst** [comment]
you don't need a gcc:i386 package, because a 64bit gcc is able to compile 32bit libs/binaries. You need a 32bit libc and other stuff

**Comment by ssokolow** [comment]
@karolherbst That was just my best guess because the 64-bit version of that package is the source of the 64-bit versions of the files the build process wants.

I also asked about a working source for them in `#ubuntu @ FreeNode` but the only answers I got were from people who hadn't realized that Ubuntu Precise's adoption of Debian's new multi-arch support means the `ia32-libs` package no longer exists.

**Comment by karolherbst** [comment]
maybe you should post your error messages. It would be easier to help then

**Comment by ssokolow** [comment]
Here's the portion of the build process that errors out:

```
Linking C executable desura_bittest
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: ld returned 1 exit status
make[2]: *** [src/executable/bittest/desura_bittest] Error 1
make[1]: *** [src/executable/bittest/CMakeFiles/desura_bittest.dir/all] Error 2
make: *** [all] Error 2
```

I then used the "skipping incompatible" lines as the starting point for a `dpkg` query, which lead me to trying `sudo apt-get install gcc-4.6:i386`:

```
ssokolow@monolith Desurium [master] % dpkg -S /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc.a   
gcc-4.6: /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc.a
ssokolow@monolith Desurium [master] % dpkg -S /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc_s.so
gcc-4.6: /usr/lib/gcc/x86_64-linux-gnu/4.6/libgcc_s.so
```

(As I mentioned, Ubuntu Precise follows Debian Wheezy in replacing `ia32-libs` and related packages with support for simply installing 32-bit and 64-bit versions side-by-side. I figured it'd be better to clear out the errors I thought to be simpler to fix first. I've never worked in anything more complicated than raw Makefiles without cmake or autotools before.)

**Comment by sorlok** [comment]
On my system, crt1.o is in /usr/lib/i386-linux-gnu, so it's definitely a 32-bit thing.

Do you have gcc-multilib installed? I was under the impression that gcc-multilib was the correct way to build 32-bit code on a 64-bit system (but please correct me if I'm wrong).

**Comment by ssokolow** [comment]
No, I didn't have `gcc-multilib` and installing it fixed the problem.

Given that most of my time as a Linux user was spent on Gentoo (where that's installed by default for 64-bit multilib profiles), no mention of it was made in the Ubuntu guide I followed for setting up multilib support (it focused on binary packages), and `install-deps.sh` doesn't try to pull it in, I think that's understandable.

Probably a good idea to update `install-deps.sh` to remedy that problem or at least display a message informing users that it's necessary for building a 64-bit Desura with support for 32-bit games.

(Though I still think this bug is unresolved since 64bit-only Desura will let you install 32-bit games without saying anything but then complain if you try to launch them.)

**Comment by Jookia** [comment]
Not installing 32-bit games is a good idea if the support isn't there.

**Comment by makson96** [comment]
It might be a good idea to somehow implement packages for 64 bit Debian/Ubuntu (for 32BIT_SUPPORT=1) in install-deps.sh.

Those missing ones are:
libc6-dev-i386, gcc-multilib

**Comment by ssokolow** [comment]
[This StackOverflow question](http://stackoverflow.com/questions/106387/is-it-possible-to-detect-32-bit-vs-64-bit-in-a-bash-script) suggests checking using one of the following methods:
- `[ `getconf LONG_BIT` = "64" ]`
- `[ `uname -m` == 'x86_64' ]`

`getconf` comes from the `libc-bin` package. It seems to be pulled in by default on Debian (it's on my VirtualBox minimal 128MiB VPS test VM) but, given that Debian includes aptitude and Ubuntu doesn't by default, that's no guarantee for Ubuntu. (It's on my Ubuntu, but it could have been pulled in by `build-essential` for all I know).
