### ISSUE TITLE
Updating in FOSS?

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#25]
Why is the updater needed? Maybe it should be removed since package maintainers should be doing it..

**Comment by Jookia** [comment]
It also complains about lack of build ID in Desurium.

**Comment by lodle** [comment]
Updater should be removed. Ill have a look at the id issue.

**Comment by Jookia** [comment]
I don't have the knowledge of the code base to remove the updater, could you do that sometime?

**Comment by lodle** [comment]
updater is removed. check my last commits

**Comment by Jookia** [comment]
Have you pushed them to the repo?

**Comment by yurikoles** [comment]
Hey, where is coomit?

**Comment by Jookia** [comment]
We're just discussing all this right now, I have no idea if Lodle's even removed it.

**Comment by lodle** [comment]
Should be removed

**Comment by Jookia** [comment]
But don't we still get polling errors?

**Comment by Jookia** [comment]
Alrighty, two latest commits fixed up this whole fiasco.
