### ISSUE TITLE
There's a wiki?

### ISSUE THREAD

**Issue by Smilex** [desura/Desurium#250]
Have https://github.com/lodle/Desurium/ point to the wiki, preferably as visible and early on the page as possible.

**Comment by Jookia** [comment]
There's a wiki tab.

On Wed, Jun 20, 2012 at 12:25 AM, Ian T. Jacobsen <
reply@reply.github.com

**Comment by Smilex** [comment]
yeah, but I ignored it because it didn't have any numbers on it, which I thought meant it didn't have any entries. But still, I think that the more you point to it, the better

**Comment by Jookia** [comment]
Consult GitHub on that. You can't get any more obvious than a 'wiki' button
next to the 'source' and other buttons.

On Wed, Jun 20, 2012 at 4:42 AM, Ian T. Jacobsen <
reply@reply.github.com

**Comment by Smilex** [comment]
well, this is unnecessary then, closing.
