### ISSUE TITLE
 boost doesnt build with glibc 2.16.0-1

### ISSUE THREAD

**Issue by matthiaskrgr** [desura/Desurium#263]

**Comment by TheSiege** [comment]
get your distribution to backport this fix: https://svn.boost.org/trac/boost/ticket/6940
(also here: https://bugs.gentoo.org/show_bug.cgi?id=424906)
or wait until we ported to boost filesystem v3 and use boost-1.50 instead

**Comment by karolherbst** [comment]
if you want you can try out the boost_fs3 branch. At the moment it compiles against boost::filesystem3, but I'm not sure if these changes https://github.com/lodle/Desurium/compare/master...boost_fs3#L3L370 are right. I'm writing some test cases for the util_fs library.
