### ISSUE TITLE
how to handle versioning in desurium

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#266]
We should talk about how to handle versioning inside desurium.

For me a branching system (like in mesa or Linux) won't make sense for me, because we don't want to "support" old versions and just rely on the newest one.

As anagromataf said in IRC, the "wine"-system would be a good one. So we would have a "stable" version-branch and an "unstable" version-branch at the same time. So we would try out things in the unstable one and push them into the stable one after a while.

Do you have any other ideas or aspects?

**Comment by makson96** [comment]
It's seem to good idea, but I have few concerns. Were you already thinking about version numbering? At the moment the original Desura client is having different version number for each platform. Do you want to unify it or keep it that way? Also the version number is stored in file "version", which looks like that:
"BRANCH=100
BUILD=21"
Do you want to stick to that solution or change it?

**Comment by TheSiege** [comment]
internally we need the desurium client to advertise desura versions;
But I think we should hide that a bit and have a "normal" version system like 0.1 and stuff.

karolherbst pointed out we'd rely a lot on pull requests then; my proposal for pull request testing:
 my idea would be no or only one compile test for small changes (like typos); three different distros for medium changes (like cmake changes); and gentoo/fedora/ubuntu/arch + whatever for heavy changes (like system_wx port)

**Comment by karolherbst** [comment]
I will write a draft where it will be explained, how we want to manage the whole releases, branches and testing stuff. Maybe I will need a week, I don't know because I'm a bit busy now.

**Comment by Cheeseness** [comment]
I forgot about this until today when I put something else into the wiki, but does anybody think there's value in taking the previous Desura versioning scheme into consideration?
https://github.com/lodle/Desurium/wiki/Application-Version-Scheme

**Comment by LiamDawe** [comment]
Is there anything wrong with using a date release version? As in Desurium 03082012 for today for example. I much prefer date versions.

**Comment by Cheeseness** [comment]
One of the main reasons for versioning is to indicate that something has changed. Date based versioning goes against this, IMO.

Dates are easily storable as metadata or published through other means, so having version numbers indicate the scope of changes between releases makes more sense to me.

**Comment by karolherbst** [comment]
mhh idea: version numbers for stable, date for unstable, testing builds

**Comment by Cheeseness** [comment]
Date makes sense for nightlies/weeklies or whatever, but even for testing builds, I think proper version numbers are worthwhile.

**Comment by karolherbst** [comment]
we should finish this in our first milestone

**Comment by karolherbst** [comment]
I've added some version information to the milestones

Further I will create a wiki page for this today or tomorrow
