### ISSUE TITLE
Desurium or Desura?

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#27]
The names are mixed due to the different branding.

**Comment by lodle** [comment]
Trying to use Desurium every where and only Desura for the official build. If you find instances of Desura in the client please let me know. Ill be moving the Desura wiki over soon.

**Comment by Jookia** [comment]
'desura' is used as the configuration save file, and in the about box IIRC.

**Comment by Protektor-Desura** [comment]
I wonder if there would be a way to set this as a variable so you don't have to remember to hunt down everywhere you need to change the name. Seems like it might make your lives easier, but maybe that's just me.

**Comment by Jookia** [comment]
I suggest we set aside a 'Desurium' day to hunt down and change the instances. One problem is the configuration directory, though. I suggest we look at the Chormium project's way.

**Comment by Jookia** [comment]
I think instead of changing everything to 'Desurium', we make sure it's all 'Desurium' except for the branding.
