### ISSUE TITLE
Get rid of the version file

### ISSUE THREAD

**Issue by Smilex** [desura/Desurium#277]
Currently some version data is read from a file found along side the executable, which should be unnecessary because the file doesn't hold enough data to justify it, and reading from files takes an unnecessary amount of time.
Currently I don't know exactly what these version numbers are used for, except as a replacement to Microsoft Windows registry keys, used by MySQL database code.
The version data is gathered from the functions GetAppBuild() and GetAppBranch(), which are found in src/static/util/code/UtilLinux.cpp

**Comment by lodle** [comment]
These are used by the official desura build to know when to upgrade.

**Comment by Smilex** [comment]
I might not be a professional in the area, but I'm pretty sure having the version data as a constant in the program itself, is not a problem when it comes to version checking.

**Comment by lodle** [comment]
This file is generated from the web server. Much easier than updating a constant.

**Comment by Smilex** [comment]
But isn't the executable updated when updating? I'm assuming that this version number is sent to the Desura servers, to check if an update is available, and if so, download it and install it.

**Comment by karolherbst** [comment]
we don't need such a mechanism in desurium, because it should be updated by the package manager of the distribution. Okay we could do some checks against github or something, but I don't have a strong opinion here.

We can include the current version via cmake (configure a file, which is just easy) and include it instead of the other files (like in an official build)

**Comment by karolherbst** [comment]
I will remove this file only for the FOSS build. The desura build will be able to use this file.

The version of Desurium will be configured via cmake, so it will be hardcoded in the binaries.
