### ISSUE TITLE
Deleting $XDG_CONFIG_HOME/desura breaks deleting the lock.

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#28]
When closing Desurium, I get the error:

```
09:17:51: Error: Failed to remove lock file '/home/jookia/.cache/desura/applock' (error 2: No such file or directory)
```

This is because I remove the $XDG_RUNTIME_DIR/desura directory before the lock is deleted.

**Comment by lodle** [comment]
Manually removed?

**Comment by Jookia** [comment]
No, I delete it before it's removed by the lock, thus it fails.

**Comment by lodle** [comment]
so delete it after the lock?

**Comment by Jookia** [comment]
I still haven't located the lock.

**Comment by lodle** [comment]
its in uicore.cpp it gets destroyed when uicore gets unloaded

**Comment by Jookia** [comment]
I'll have to check that out sometime when I'm not half asleep.

**Comment by ghost** [comment]
The question is what do you expect from Desurium when it is encountering abnormal condition? This message is good thing here because lock file shouldn't be removed by hand. IMO Lack of ability to remove non-existent file in case of destroySingleInstanceCheck() isn't a problem, right?

**Comment by Jookia** [comment]
Upon further inspection, this is due to the lock being deleted first, and the folder being deleted between. Or something. This is a complex problem.

Also, I should clarify: Desura deletes the cache folder, lock is in cache folder. Our lock.

**Comment by ghost** [comment]
hm. Looks like you have collision between XDG variables. In my case syscall flow looks like given below:

open("/<user home>/.desura/.applock", O_WRONLY|O_CREAT|O_EXCL, 0600) = 3
...
chmod("/<user home>/.desura/.applock", 0600) = 0
...
unlink("/<user home>/.desura/.applock") = 0

In your case the problem probably lays here:

src/static/util/code/UtilLinux.cpp:

856         if (getenv("XDG_RUNTIME_DIR") == 0)
857         {
858                 printf("$XDG_RUNTIME_DIR not set, falling back to $XDG_CACHE_HOME.");
859 
860                 if (setenv("XDG_RUNTIME_DIR", cacheDirString.c_str(), 0) == -1)
861                 {
862                         printf("Failed to setenv $XDG_CONFIG_HOME.");
863                         return true;
864                 }
865         }

I think that fallback/value for $XDG_RUNTIME_DIR should be ${HOME}/.desura not $XDG_CACHE_HOME. Also - in line 862 should be $XDG_RUNTIME_DIR' not `$XDG_CONFIG_HOME.

You can test that by exporting XDG_RUNTIME_DIR with proper value to current shell from which Desura/Desurium will be fired-up. If this will be fine I will manage fix.

**Comment by Jookia** [comment]
XDG Base Directory Specification 0.7 requires that XDG_CACHE_HOME be a special folder with special requirements. ~/.desura doesn't cut this. Neither does the proper config directory.

Thanks for the note about line 862, I'll fix that.

I just set XDG_RUNTIME_DIR explicitly before running Desurium and the error still happened.

**Comment by ghost** [comment]
I read this specification but this is about $XDG_RUNTIME_DIR not $XDG_CACHE_HOME. falling back to $XDG_CACHE_HOME... Well, isn't best idea. Those should be _separate_ directories - they have different functions.

**Comment by Jookia** [comment]
If you want to argue over XDG_RUNTIME_DIR falling back to the cache dir, please make another issue. This is for the lock error, and at the moment the lock code is failing, due to what I suspect being the lock trying to delete itself twice.

**Comment by ghost** [comment]
Direct reason and explanation of problem described by you in this ticket/issue is this fallback - so fix I'm suggesting is addressing it perfectly. I don't see any sense of creating another issue for this...

**Comment by Jookia** [comment]
While I am building Desurium with the fix of yours to test it, how come the message says '/home/jookia/.cache/desura/applock' instead of '//desura/applock'?

**Comment by ghost** [comment]
hmm, looks like I accidentally misused github's markup. between slashes there should be home dir. Like:

unlink("/var/playerone/.desura/.applock") = 0

that's all the story :)

**Comment by Jookia** [comment]
Are you using the latest commit? /home/fred/.desura is no longer used.

**Comment by Jookia** [comment]
Okay, changing the code to this:

```
    if (setenv("XDG_RUNTIME_DIR", "/home/jookia/.config", 0) == -1)
    {
        printf("Failed to setenv $XDG_RUNTIME_DIR.");
        return true;
    }
```

Still yields the error message:

> (8871, son of 8795) src/shared/uicore/code/UICoreMain.cpp:498 - OnExit wxAPP
> 00:37:04: Error: Failed to remove lock file '/home/jookia/.config/desura/applock' (error 2: No such file or directory)

If you have any other ideas for a fix, I'm all ears.

**Comment by ghost** [comment]
Do strace on your Desurium from firing-it up to exiting process like:

strace -f -s 8192 -o desurium.strace bash -c './desura'

Then try to grep for lines with applock or .config - this should shed some light on our problem. Thanks in advance.

**Comment by Jookia** [comment]
Cheers man, I didn't know how to use strace like that, thus I didn't see this stuff a few days ago.

> 10190 unlink("/home/jookia/.config/desura/applock") = 0
> 10190 unlink("/home/jookia/.config/desura") = -1 EISDIR (Is a directory)
> 10190 rmdir("/home/jookia/.config/desura") = 0
> 10112 unlink("/home/jookia/.config/desura/applock") = -1 ENOENT (No such file or directory)

This is the output I get, and is exactly what I've suspected the entire time, and something I saw earlier. Two UICore objects are being created, thus two locks are being created. In fact, a quick grep/ack reveals this:

> [jookia@jookia-arch src]% ack --ignore-dir "third_party" "UICore g_"
> shared/uicore/code/UICoreEntry.cpp
> 283:UICore g_pUICore;
> 
> shared/utilcore/code/UtilCoreEntry.cpp
> 159:UICore g_pUICore;

A few days ago I tried moving the folder deletion code, but it seems the problem isn't just with the folder being deleted, but rather that the lock is trying to be deleted twice. I'd have to move the deletion code in to bootloader_lin, which is something I don't want to do.

I propose we either use one big UICore global, I'm not sure how Lodle would like that, or that we move the lock code (in this case it's a single instance check).

**Comment by ghost** [comment]
OK. Good - something else then I assumed (not the effect but the reason of it) I must admit. But there is a progress anyway! Yeah, let's check Lodle for his position/opinion.

**Comment by Jookia** [comment]
Since it's 1AM, I doubt Lodle will have much to say. Maybe drop by the #desura freenode channel for kicks though?

**Comment by ghost** [comment]
that's also an option but I think we can wait for him if you are OK with that.

**Comment by Jookia** [comment]
I'm waiting sure, but #desura is lonely and we're discussing XMPP stuffs.

**Comment by lodle** [comment]
What is going on is that the parent process forks and then the child loads uicore and goes on thus uicore gets duplicated. The parent should disable the single instance check. The reason for this is that if the child crashes the parent can process it.

Looks like the parent is not disabling the single instance check.

**Comment by Jookia** [comment]
So this is a bug in your area?

**Comment by Jookia** [comment]
Fixed in my issue 80 branch. Will be merged tomorrow.
