### ISSUE TITLE
patch needs to be included in install-deps for fedora and some perl md5 disgest stuff

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#280]
patch needs to be included in install-deps for fedora
tested on clean fedora 17 install
Desurium/cmake/scripts/patch.sh" line 19: patch: command not found
also http://pastebin.com/Wv6RTmqX happens which I fixed with installing
perl-Digest-MD5

**Comment by karolherbst** [comment]
we should check this also in cmake, see #243
