### ISSUE TITLE
Testing building on Windows

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#289]
I will take it upon myself to do the Windows testing of the builds for you guys, so you can have me as your windows guy.

First question while i download all the required programs;

" Note: Make sure you add git to your environment path and also set SVN_PATH to point to the tortoise svn path

Open a 32bit cmd.exe with env vars set up by vc or other scripts (so we have a full build environment)
run ./build_desura.bat
wait"

The instructions aren't exactly clear, they need to be a bit more step by step for me (that's if you want my help).

How do i set the paths and to where? How do i "with env vars set up by vc or other scripts (so we have a full build environment)".

If someone can make a more step by step i can see if it compiles and runs for you.

**Comment by LiamDawe** [comment]
Sorry guys i really dont have the time someone else will need to do this.

**Comment by karolherbst** [comment]
I will start working on that, because we reached the 0.8 milestone

**Comment by lodle** [comment]
not needed as linden will be doing windows testing
