### ISSUE TITLE
some "rules" for desurium developers

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#294]
Yesterday I created a wiki-page: https://github.com/lodle/Desurium/wiki/Working-with-git-and-github

I think it is necessary to have a rule base for the work on Desurium.

It should be accepted by the current "main" contributors:
- lodle
- karolherbst
- Cheeseness
- Jookia
- matthiaskrgr

these rules should count for everyone (without exceptions).

**Comment by Jookia** [comment]
I think they're great guidelines.

**Comment by karolherbst** [comment]
okay, I think this is okay now. Nobody screamed, so I will see this as finished
