### ISSUE TITLE
Give an option to be FHS compliant

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#296]
A few hours ago I chatted a little with an openSUSE (@Mailaender) and an Gentoo (@hasufell) package maintainer. the rpm based distro would like an option to be FHS (https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) compliant; while the Gentoo person demands it in order to be in the repositories. Essentially we have been FHS compliant one time but this: https://github.com/lodle/Desurium/commit/07fde3828d86c2ce81d29bea2984a48b42af43c1 commit broke it.

EDIT: karolherbst

we have to do this:
- create a system_path API
- let cmake configure a source file, so we have this absolute paths insource
- allow cmake to specify every needed path in an absolute way
- use the system_path API in the code

**Comment by Jookia** [comment]
I'd like to know how that commit broke it. The behaviour is the same. To my knowledge Desurium is FHS compliant.

**Comment by karolherbst** [comment]
they want to have a possibility to install desurium in /usr and no special desurium directory

**Comment by Jookia** [comment]
Yeah, you can do that without any modification. Dump desura in /usr/games/desura, and in /usr/bin symlink the run.sh script. That's literally all you need to do.

**Comment by karolherbst** [comment]
it has to be something like this:

$PREFIX/bin/desura
$PREFIX/lib/libdesura_{webcore, uiscore, cef, wx, ...}.so or maybe $PREFIX/lib/desura/lib*.so
$PREFIX/share/desura/{desura.png, data, ..}

Jookia, no this isn't FHS compliant, because you can install desura only in its onw directory

**Comment by Jookia** [comment]
Yes, that's what I just said, EXCEPT for the libdesura_\* stuff, which is possible with a few tweaks, despite being a ludicrous idea.

**Comment by karolherbst** [comment]
and this share/desura/ stuff

**Comment by hasufell** [comment]
No, this is not sufficient, the general requirements are:

binary destination modifiable (not just the prefix)
library destination modifiable (meaning support for lib appendix like lib64, probably better use GNUInstallDirs for this)
datadir destination modifiable (not just the prefix)

do something like
set(BINDIR "bin" CACHE STRING "Where to install binaries")
or use "GNUInstallDirs" module

wesnoth build system may be a good example http://svn.gna.org/svn/wesnoth/trunk/CMakeLists.txt

**Comment by Jookia** [comment]
I'll go through it in detail:

$PREFIX/bin/desura should be a symlink to $PREFIX/share/desura/run.sh. Running

[jookia@jookia-arch ~]% file /usr/bin/\* | grep shell | wc -l # Shell scripts.
350
[jookia@jookia-arch ~]% ls -l /usr/bin | grep "-> /usr/" | wc -l # Symlinks to /usr.
47

You can see that this is normal.

$PREFIX/lib/libdesura\* is stupid as no other applications can benefit from the libraries. But it's possible to do.
$PREFIX/share/desura is where the current folder would be.

CMake supports an INSTALL_PREFIX of some kind. I know that some minor changes are needed, but overall it's fine so far.

**Comment by hasufell** [comment]
the prefix is useless.

**Comment by Jookia** [comment]
$PREFIX is metaphorical.

**Comment by hasufell** [comment]
CMAKE_INSTALL_PREFIX is useless, the absolute paths need to be modifiable.

one might say this is more than FHS compliance, but that's the only way to ensure all kinds of distributions can handle this package with ease

but it may not be sufficient to fix this in the build system, cause it can break the code, I didn't have a closer look yet

**Comment by Mailaender** [comment]
/usr/games is not allowed at http://build.opensuse.org/ as well as binaries in /usr/share are forbidden. I also tried moving and linking everything to FHS compliant folders which went horribly wrong (Desurium did not find images/skins/languages/libraries). I am currently putting everything into /opt/desurium but I don't know if this will be accepted in openSUSE games.

**Comment by hasufell** [comment]
but /usr/games is allowed as per FHS: http://www.pathname.com/fhs/pub/fhs-2.3.html
as well as /usr/share/games

**Comment by Jookia** [comment]
In IRC I was informed that you can't put binaries in /usr/share. Which makes sense, I just didn't know it.

So what it looks like is that we should put libs in /usr/lib/desura/*.so as zsh does something like this, the binary in /usr/bin and the data in /usr/share/desura. It shouldn't be too hard to fix the code.

**Comment by karolherbst** [comment]
Jookia but desura should also be able to install in /opt (would be good for propritary release) and /usr/games (just to separate from "normal" system).

I like the idea to create a system_path.h file by cmake and use values stored there for library and data loading. And add cmake options like the ones in configure scripts

**Comment by hasufell** [comment]
@Jookia 
That's not sufficient for gentoo as stated above.

gentoo uses FHS compliant _defaults_ which are
"/usr/games/bin" for binaries
and
"/usr/games/libAPPENDIX/PACKAGENAME" for libraries
as well as
"/usr/share/games/PACKAGENAME" for datafiles

the rest (like icons, desktop files etc) go in the standard locations

On top of that we give the user the possibility to change all of those games-related destinations which means they have to be _fully_ modifiable.

In the end we have our ways to hack around things when upstream does not provide this possibility, but that's not nice at all.

**Comment by Jookia** [comment]
@karolherbst It should be, but if we're making the code do it all we have to do is #ifdef out code and rewrite it.

@hasaufell But of course. Sorry, I'm speaking from an Arch Linux perspective. karolherbst would have to edit the build system with that.
