### ISSUE TITLE
Force update shortcut errors out

### ISSUE THREAD

**Issue by lodle** [desura/Desurium#30]
http://www.moddb.com/groups/desura/forum/thread/unknown-desura-link-f

**Comment by Jookia** [comment]
Is this technically a Desurium error if the updater is ripped out?

**Comment by lodle** [comment]
not really, but is for nongpl build

**Comment by Jookia** [comment]
Well I don't have access to work on the non GPL build for reasons which must be obvious, so I don't think I'll be fixing it.

**Comment by lodle** [comment]
more of a reminder for me :P

**Comment by Jookia** [comment]
Alrighty.

**Comment by Jookia** [comment]
Is this still relevant?
