### ISSUE TITLE
RPMlint warnings

### ISSUE THREAD

**Issue by Mailaender** [desura/Desurium#301]
as requested in IRC... RPMlint tells me about:

```
W: non-executable-script /opt/desurium/scripts/launch_xdg_template.sh 0644L /bin/bash
W: non-executable-script /opt/desurium/scripts/launch_bin_template.sh 0644L /bin/bash
This text file contains a shebang or is located in a path dedicated for
executables, but lacks the executable bits and cannot thus be executed.  If
the file is meant to be an executable script, add the executable bits,
otherwise remove the shebang or move the file elsewhere.
```

I don't know if it is a problem about my packaging, should remain non-executable or if this could be resolved in your cmake scripts.

Other warnings include:

```
Desurium.i586: W: file-contains-date-and-time /opt/desurium/lib/libcef_desura.so
Your file uses  __DATE and __TIME__ this causes the package to rebuild when
not needed

Desurium.i586: W: file-contains-current-date /opt/desurium/lib/libuicore.so
Your file contains the current date, this may cause the package to rebuild in
excess.

Desurium.i586: I: binary-or-shlib-calls-gethostbyname /opt/desurium/lib/libwx_gtk2u_desura-2.9.so.3
The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```

which has something to do with IPv6 compatibility (or the lack thereof) http://en.opensuse.org/openSUSE:Packaging_checks#binary-or-shlib-calls-gethostbyname

and issue #296

```
Desurium.i586: W: suse-filelist-forbidden-opt /opt/desurium is not allowed for official SUSE packages
/opt may not be used by a distribution. It is reserved for 3rd party packagers
```

Binary files in `/usr/share` is also forbidden. http://en.opensuse.org/openSUSE:Packaging_checks#arch-dependent-file-in-usr-share and putting everything in `/usr/games` will also get the package deleted after building it.

**Comment by posophe** [comment]
Hi !

Change permissions by attr or defattr with 644 into %files section. If you use %{_prefix} for cmake prefix config, you don't need to use a script for launching desura. I never successfully build desura can you send me your specfile please

Best regards.

Posophe

**Comment by Mailaender** [comment]
I am currently building pull request #303 with https://build.opensuse.org/package/view_file?file=Desurium.spec&package=Desurium&project=home%3AMailaender

**Comment by posophe** [comment]
Ok thx for your spec file.
@+

Posophe
