### ISSUE TITLE
List Games & CDKeys

### ISSUE THREAD

**Issue by Protektor-Desura** [desura/Desurium#32]
We should add to the Tools menu under the Desura icon a link that takes you to the web page where it lists all the games you own and all the CDKeys for each game that needs it. There are other ways to get to it but it is pretty buried and if you don't know where it is your likely to miss it.

The URL is:
https://secure.desura.com/cart/cdkeys

It is the same URL for everyone and they just need to be logged in to get the list.

**Comment by Jookia** [comment]
Sounds great!

**Comment by Jookia** [comment]
Done in the listkeys branch of my fork. It needs testing.

**Comment by Jookia** [comment]
Merged a while back.
