### ISSUE TITLE
install from desurium ppa doesnt work

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#321]
So i tried the ppa available for desurium and it no longer launches, the launcher goes to:
/opt/desurium/run.sh

But it doesn't seem to exist anymore? It used to work now it doesn't?

**Comment by karolherbst** [comment]
we have implemented full FHS support

see #303 and #296, also run.sh is renamed to desura within the install step

**Comment by LiamDawe** [comment]
What do I need to tell the packager to change to fix it?

**Comment by karolherbst** [comment]
change paths, you could look into the ebuild for example

**Comment by LiamDawe** [comment]
I have sent a message to the PPA owner of the Desurium builds for *buntu

**Comment by LiamDawe** [comment]
The PPA owner emailed me to say he's on it, just waiting for launchpad to build it :)
