### ISSUE TITLE
32 bit games do not start on 64 bit system.

### ISSUE THREAD

**Issue by makson96** [desura/Desurium#324]
This seems to be regression. In August, when I build Desurium with -D32BIT_SUPPORT I was able to play 32 bit games. Now (at least since 09.09.2012) I cannot do that. I get error:

11:31   Failed to launch item.: You need 32 bit libraries to play this game [75.0]

Tested on Trine 2 and Sacred Gold. If I start games manually from the install directory, they work fine.

**Comment by karolherbst** [comment]
It could be, that my FHS changes broke something

**Comment by Jookia** [comment]
Yes, ItemHandle_Nix calls desura_bittest.

**Comment by karolherbst** [comment]
the 32BIT_SUPPORT cmake variable has to be set to ON for this. We should get rid of this completly and use other runtime checks instead.

**Comment by makson96** [comment]
I was inaccurate. Even if it set to on  -D32BIT_SUPPORT=ON the 32 bit games will not start.

**Comment by karolherbst** [comment]
I will add several implementation for a 32bit check
- bittest
- kernel config check (/proc/config.gz)
- ...

others

@makson96 I tested it here with VVVVV and it worked for me. Do you use a local compilation or a system wide installation? More information is needed to be able to debug it probably.

**Comment by makson96** [comment]
I can reproduce the issue on 64 bit Ubuntu 12.04.1 LTS with ia32-libs install by simply:

git clone git://github.com/lodle/Desurium.git
cd Desurium
sudo sh install_deps.sh
mkdir build
cd build
cmake -D32BIT_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=../install ..
make install
cd ../install
./desura

What more info do you want? How Desurium detect 32 compatibility? Maybe I am missing some 32 bit libs, which are not required by games, but by Desurium only? I also want to remind, that everything was working correctly back in August.

VVVVV has 64 version which work fine for me. I am unable to start 32 bit version of VVVVV with the same error.

**Comment by karolherbst** [comment]
okay, here desurium was using the desura_bittest executable from my system wide installation.

Confirmed.
