### ISSUE TITLE
User avatar not respecting proper alpha

### ISSUE THREAD

**Issue by meklu** [desura/Desurium#329]
The client seems to only support 1-bit alpha in avatars in the top left of the window (next to the menu button). It ignores semi-transparent pixels and applies full alpha to them.

**Comment by ssokolow** [comment]
I've been meaning to report this for a while but kept forgetting. One of my friends has an avatar which runs afoul of this limitation.

**Comment by karolherbst** [comment]
I never checked it so I did not add it to milestone, but it seems, that this bug exists :p

**Comment by karolherbst** [comment]
Here it seems, that a "mask" is laying on top of the picture, which is killing some stuff part of the pictures with alpha < 0.5

The shown parts should have an alpha value.

**Comment by ssokolow** [comment]
@karolherbst Wouldn't help with stuff like the round image my friend uses. His problem is an ugly, jagged, pixely outer edge which he can't resolve by uploading a pre-blended image because the client and the Desura site use different background colors and patterns.

What really needs to be done to fix this is proper alpha-blending in the client so it matches the effect on the Desura site.

**Comment by lodle** [comment]
Alpha transparency is a pain and i did spend some time trying to get it to work. Good luck!

**Comment by karolherbst** [comment]
it is working for me here on Linux.

Did you read this?:

"Alpha channel support

Starting from wxWidgets 2.5.0 wxImage supports alpha channel data, that is in addition to a byte for the red, green and blue colour components for each pixel it also stores a byte representing the pixel opacity.

An alpha value of 0 corresponds to a transparent pixel (null opacity) while a value of 255 means that the pixel is 100% opaque. The constants wxIMAGE_ALPHA_TRANSPARENT and wxIMAGE_ALPHA_OPAQUE can be used to indicate those values in a more readable form.

While all images have RGB data, not all images have an alpha channel. Before using wxImage::GetAlpha you should check if this image contains an alpha channel with wxImage::HasAlpha. Currently the BMP, PNG, TGA, and TIFF format handlers have full alpha channel support for loading so if you want to use alpha you have to use one of these formats. If you initialize the image alpha channel yourself using wxImage::SetAlpha, you should save it in either PNG, TGA, or TIFF format to avoid losing it as these are the only handlers that currently support saving with alpha."

http://docs.wxwidgets.org/trunk/classwx_image.html

see here for older versions (even 2.9.3):

"Note that currently only images loaded from PNG files with transparency information will have an alpha channel but alpha support will be added to the other formats as well (as well as support for saving images with alpha channel which also isn't implemented)."

http://docs.wxwidgets.org/2.8/wx_wximage.html

**Comment by lodle** [comment]
i dont think windows supports drawing alpha properly even if wx can load it but not sure about gtk.

**Comment by karolherbst** [comment]
@meklu @ssokolow: is it fixed with #346?

**Comment by ssokolow** [comment]
@karolherbst At the moment, I'm really not in a position to test it:
- I deleted my clone about a week ago in favor of makson96's weekly PPA (Which I'd already been running for months)
- My schedule is currently quite busy
- It's my friend's avatar that contains transparency, not mine.

...but I think my friend is also on makson96's PPA, so I should be able to give you a confirmation of whatever @meklu says within a week of the changes getting merged into master.

**Comment by karolherbst** [comment]
okay, then I will merge these changes. I will pick them into 0.8 branch after confirmation

**Comment by ssokolow** [comment]
Seems to be fixed. The rounded boundary of his avatar is now nice and smooth.
