### ISSUE TITLE
Upload & Download issue

### ISSUE THREAD

**Issue by Protektor-Desura** [desura/Desurium#33]
This one is going to be a pain in the behind to find. Consitantly but with no rhyme or reason the Linux client will crash and exit when doing an upload. The Windows version doesn't seem to have this problem. Sometimes it happens immediately when you try and start the upload sometimes it take as long at 10 minutes. It always crashes though before the upload is finished unless it is a small file like under 10 megs. Most updates to games are this small but getting a game up under Linux it always crashes multiple times and I have to resume it.

Less frequent is the crash on download. I have I would say maybe 5% of the time the client will crash on a download both on Windows and Linux. 

I do way more uploading and downloading than most do with the client, so I see it all the time, but I am getting reports from developers and users of this issue.

**Comment by Jookia** [comment]
Could you please enable core dumping on Linux and then reproduce the error?

**Comment by Protektor-Desura** [comment]
I have tried over and over with Iodle to run gdb with it and I don't believe we ever found anything useful. I will try the coredump route since it is very easy to make it crash.

**Comment by Protektor-Desura** [comment]
I will say I didn't notice the upload and download problem about 4-6 versions back of the client. So something was added to that section of the code or passed to that section of the code that is causing this. Basically once upon a time it worked fine, but now it doesn't.

**Comment by LiamDawe** [comment]
Not that i know much about anything just chiming in as usual, but when under Linux do you run it in terminal each time to catch any messages?

**Comment by Protektor-Desura** [comment]
Yes there are no error messages that are created when it is run from the terminal.

**Comment by LiamDawe** [comment]
Does Desura supress info in the terminal? I've had it crash plenty of times and terminal literally displays nothing.

**Comment by Jookia** [comment]
If it knew it was going to crash, it probably wouldn't crash in the first place. ;)

**Comment by Protektor-Desura** [comment]
This is not limited to just the Linux version. The Windows client has the same issue but it is pretty rare that the bug pops up in the Windows client.

**Comment by Protektor-Desura** [comment]
I guess I should say this again the Windows upload and download seems pretty stable to me. I rarely (0.5%) have any troubles with uploading and downloading using the Windows client. The Linux client is bad. For me uploading is 100% failure it will always fail on large uploads. Downloading isn't as bad more like 5%-10% of the time it will crash on download. This is out of hundreds of downloads. If you are not seeing the download crashing then I am not surprised given the amount of uploading and downloading I do.

**Comment by Jookia** [comment]
Hmm.. Lodle may know about any Unix-specific code to do with the crash.

**Comment by Jookia** [comment]
Fixed.

**Comment by Jookia** [comment]
Apparently this isn't fixed.

**Comment by Jookia** [comment]
False ... false.
