### ISSUE TITLE
Too few arguments with libnotify 0.5.2

### ISSUE THREAD

**Issue by oldtopman** [desura/Desurium#330]
When compiling Desurium on Slackware 13.37 x86_64, I get this error:

```
[ 39%] Building CXX object src/static/wx_controls/CMakeFiles/wx_controls.dir/code/gcTaskBar.cpp.o
/home/oldtopman/tmp/Desurium/src/static/wx_controls/code/gcTaskBar.cpp: In member function 'bool gcTaskBarIcon::ShowBalloon(const wxString&, const wxString&, unsigned int, int)':
/home/oldtopman/tmp/Desurium/src/static/wx_controls/code/gcTaskBar.cpp:309:8: error: too few arguments to function 'NotifyNotification* notify_notification_new(const char*, const char*, const char*, GtkWidget*)'
/usr/include/libnotify/notification.h:79:21: note: declared here
make[2]: *** [src/static/wx_controls/CMakeFiles/wx_controls.dir/code/gcTaskBar.cpp.o] Error 1
make[1]: *** [src/static/wx_controls/CMakeFiles/wx_controls.dir/all] Error 2
make: *** [all] Error 2
bash-4.1$
```

**Comment by Jookia** [comment]
You need a newer libnotify. I think there may be an ifdef in the code to compensate for the API change, but that's what it boils down to.

**Comment by karolherbst** [comment]
We discussed this already in IRC. Currently I don't know how to handle the fourth argument (GtkWidget*). It would be easier to check for a libnotify version we can handle, because 0.5.2 is really old.

**Comment by oldtopman** [comment]
Any workarounds would be preferred, as upgrading requires installing gnome-common, rebuilding wxGTK, and who knows what else.

**Comment by karolherbst** [comment]
the dependencies of libnotify are these:

glib
gdk-pixbuf
gtk-doc-am
pkgconfig

if you have these libraries installed, you should be able to build your own libnotify. There is not a single dependency to any gnome relevant stuff. If your distribution wants to install gnome-common, then report a bug there.

I don't know if the rebuilding of wxGTK would make sense, but there aren't any (direct) dependencies from wxGTK to libnotify.

**Comment by karolherbst** [comment]
maybe libnotify 0.6.x is a working version, but I don't know. Currently it isn't that easy for me to use an older libnotify (below 0.7).

Maybe there is something written in the API description of libnotify. I will read them later this day
