### ISSUE TITLE
Exit on Upload Close

### ISSUE THREAD

**Issue by Protektor-Desura** [desura/Desurium#345]
Sometimes when you are uploading a MCF on the current client (lodle-Desurium-5198939) when the upload load is done and you click on close to close the upload windows the client will exit/crash completely.

**Comment by karolherbst** [comment]
I can't test things like that, because I don't have an account for uploading stuff.

**Comment by Protektor-Desura** [comment]
Send your Desura username to support and I will set you up with access to the test game profile and you can use that to test it. So far every single time I close the upload window it causes the client to exit.

**Comment by karolherbst** [comment]
done
