### ISSUE TITLE
real minor styling issue - black lines between page names

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#353]
Okay hard to title this one right now.

Basically on my RC3 installed via the PPA when you go to a page so say a project zomboid screenshot between each page in the breadcrumb nav there is a thick black _ between each page name under the slashes.

If possible should include this fix for RC4 since it's just a tiny bit of polish.

Screenshot: http://www.gamingonlinux.com/junk/rc3bug.png

**Comment by lodle** [comment]
This looks like the text is 1 pix taller than the separator which then shows the background of the panel. Shouldnt be to hard to fix.

**Comment by karolherbst** [comment]
isn't this #213?

**Comment by LiamDawe** [comment]
Oops you are right.
