### ISSUE TITLE
curl needs the -L option passed in order to reliably download tarballs on github

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#356]
as stated here:
https://help.github.com/articles/downloading-files-from-the-command-line
curl needs the -L option passed in order to reliably download tarballs
this makes it possible to download some tarballs in the build script
as otherwise 

```
<html><body>You are being <a href="http://cloud.github.com/downloads/lodle/Desurium/breakpad-850.tar.gz">redirected</a>.</body></html>
```

or similar occurs (wget works nonetheless)

**Comment by karolherbst** [comment]
not a bug within our cmake files, please report to cmake instead

**Comment by karolherbst** [comment]
detail explanation:

ExternalProject is using file(DOWNLOAD ...) internally to download files. Cmake is using curl as a backend. There is nothing I can do, without breaking future version or changing of behavior of one of the parties. This could be also a distribution bug.
