### ISSUE TITLE
create alternative to MFC (Microsoft Foundation Classes)

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#376]
see here: http://social.msdn.microsoft.com/forums/en-US/Vsexpressvc/thread/7c274008-80eb-42a0-a79b-95f5afbf6528/

MFC is only available in NON FREE versions of visual studio. So either you have to be a student (with free access to a professional or ultimate versions of VC) or have to pay a lot of money for it.

This should never be a requirement to build free softwware

Any comment from @lodle  about this?

**Comment by karolherbst** [comment]
I think WTL would be a good alternative: http://sourceforge.net/projects/wtl/

but then we are not able to build with mingw, which is not a big problem, because CEF won't build with mingw currently

**Comment by karolherbst** [comment]
we should clarify, if we are allowed to use MFC with a GPL codebase. Until we have done this, this is a fatal bug

**Comment by Cheeseness** [comment]
After bouncing this around with @Jookia @karolherbst and @TheSiege and doing some research, it looks like there are anti-Free Software considerations in the MFC licence terms which describes licences such as the GPL as "Excluded Licences".
