### ISSUE TITLE
Desurium wxWidgets richtext conflicts Running with Rifles

### ISSUE THREAD

**Issue by Mailaender** [desura/Desurium#380]
I can't start the game http://www.desura.com/games/running-with-rifles on openSUSE 12.2 and Desurium 0.8rc3 client:

```
rwr_config: error while loading shared libraries: libwx_gtk2u_richtext-2.8.so.0: cannot open shared object file: No such file or directory
```

I have `libwx_gtk2_richtext-2_8-0-wxcontainer`, `libwx_gtk2u_richtext-2_8-0-stl`, `libwx_gtk2u_richtext-2_8-0-wxcontainer`, `libwx_gtk2u_richtext-2_8-0-wxcontainer24c`, `libwx_gtk2u_richtext-2_9-3-compat-lib-stl` and `libwx_gtk2u_richtext-2_9-3-stl` installed.

Can't install `libwx_gtk2_richtext-2_8-0-compat-lib-wxcontainer`, `libwx_gtk2u_richtext-2_8-0-compat-lib-stl`, `libwx_gtk2u_richtext-2_8-0-compat-lib-wxcontainer` and `libwx_gtk2u_richtext-2_8-0-compat-lib-wxcontainer24c` because this will remove Desurium which depends on `libwx_gtk2u_richtext-2.9.so.3`.

**Comment by karolherbst** [comment]
strange. Normally every application should run with wx-2.9.3, because there is a compatibility layer inside. You could try to symlink this library:

libwx_gtk2u_richtext-2.8.so.0 => libwx_gtk2u_richtext-2.9.so.3

**Comment by Mailaender** [comment]
Hmm, I just removed Desurium and wxWidgets and tried a fresh reinstall of various wxWidgets APIs. Seems to be a problem on their site. Reported it at: http://www.modulaatio.com/runningwithrifles/?page_id=22#comment-5258
