### ISSUE TITLE
>=tinyxml-2.6 is required

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#393]
I found out, that we require at least tinyxml-2.6, we should check for this in the ebuild,PKGBUILD and cmake

error output with tinyxml 2.5.x on debian 6

```
[ 10%] Building CXX object src/static/managers/CMakeFiles/managers.dir/code/ThemeManager.cpp.o
In file included from /home/karol/Dokumente/Desurium/src/static/managers/code/ThemeManager.cpp:25:0:
/home/karol/Dokumente/Desurium/src/include/XMLMacros.h: In function ‘bool XML::isValidElement(TiXmlNode*)’:
/home/karol/Dokumente/Desurium/src/include/XMLMacros.h:253:22: error: ‘TINYXML_ELEMENT’ is not a member of ‘TiXmlNode’
make[2]: *** [src/static/managers/CMakeFiles/managers.dir/code/ThemeManager.cpp.o] Fehler 1
make[1]: *** [src/static/managers/CMakeFiles/managers.dir/all] Fehler 2
make: *** [all] Fehler 2
```

**Comment by Jookia** [comment]
Well we're hosting the CMake module, so adding a version check for that is easy but non-trivial. Is there a reason why we need TinyXML 2.6 specifically? Can we not work around it?

**Comment by karolherbst** [comment]
I got this build error above in my debian 6 virtual machine, where tinyxml 2.5.x was installed

**Comment by karolherbst** [comment]
I found this FindTinyXML.cmake file: https://bitbucket.org/sumwars/sumwars-code/src/8526aee7d088/CMakeModules/FindTinyXML.cmake

there is a check if the tinyxml 2.6 API exists.
