### ISSUE TITLE
fail to compile third_party/sqlite on Linux

### ISSUE THREAD

**Issue by yorikvanhavre** [desura/Desurium#406]
Hi,
I had this little problem while compiling Desurium (with todays revision, on debian testing 64bits) (I used make VERBOSE=1 to find the problematic command):

```
yorik@bilbo:~/Sources/build/Desurium/build/src/tests$ /usr/bin/c++ -fPIC -pipe
-fvisibility=hidden -finline-functions  -fpermissive -std=c++0x -O3 -DNDEBUG  -O2 
-Bsymbolic-functions -lpthread CMakeFiles/UtilLinux_test.dir/util/UtilLinux_test.cpp.o 
-o UtilLinux_test -rdynamic ../static/util/libutil.a -lboost_unit_test_framework-mt 
-Wl,-Bstatic -lboost_test_exec_monitor-mt -Wl,-Bdynamic -lbz2 ../../third_party/sqlite3x
/libsqlite3x.a ../../third_party/sqlite/libsqlite.a -lpthread -lboost_filesystem-mt 
-lboost_system-mt 
../../third_party/sqlite/libsqlite.a(sqlite3.c.o): In function `unixDlError':
sqlite3.c:(.text+0x2b6e6): undefined reference to `dlerror'
../../third_party/sqlite/libsqlite.a(sqlite3.c.o): In function `unixDlClose':
sqlite3.c:(.text+0x47b4): undefined reference to `dlclose'
../../third_party/sqlite/libsqlite.a(sqlite3.c.o): In function `unixDlSym':
sqlite3.c:(.text+0x47c7): undefined reference to `dlsym'
../../third_party/sqlite/libsqlite.a(sqlite3.c.o): In function `unixDlOpen':
sqlite3.c:(.text+0x47d9): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
```

I solved it by adding -ldl to the end of the build command (found a similar problem on the net, with the solution):

```
yorik@bilbo:~/Sources/build/Desurium/build/src/tests$ /usr/bin/c++     -fPIC -pipe 
-fvisibility=hidden -finline-functions  -fpermissive -std=c++0x -O3 -DNDEBUG  -O2    
-Bsymbolic-functions -lpthread CMakeFiles/UtilLinux_test.dir/util/UtilLinux_test.cpp.o  -o 
UtilLinux_test -rdynamic ../static/util/libutil.a -lboost_unit_test_framework-mt -Wl,-Bstatic 
-lboost_test_exec_monitor-mt -Wl,-Bdynamic -lbz2 ../../third_party/sqlite3x/libsqlite3x.a 
../../third_party/sqlite/libsqlite.a -lpthread -lboost_filesystem-mt -lboost_system-mt -ldl
```

Sorry I didn't provide a patch, I don't really know how to adapt makefiles...

**Comment by karolherbst** [comment]
maybe you should run install-deps.sh before compiling. 

Maybe a sqlite-dev packages will be solve this problem.

**Comment by yorikvanhavre** [comment]
I ran install-deps of course, and I have libsqlite3-dev installed... Anyway, if I'm the only one experiencing this, probably it is something specific to my system, and this issue can be closed?

**Comment by karolherbst** [comment]
mhh it seems, that cmake didn't find your system wide installed sqlite3 library, because it was compiled on your system.

What is the output of

```
mkdir make_test; cd make_test; cmake ..
```

**Comment by yorikvanhavre** [comment]
Sorry for the delay!
Doing your suggestion above, it seems cmake did find the sqlite3 stuff correctly. It says:
-- Found Sqlite3 header file in /usr/include
-- Found Sqlite3 libraries: optimized;/usr/lib/x86_64-linux-gnu/libsqlite3.so;debug;/usr/lib/x86_64-linux-gnu/libsqlite3.so
If I understand correctly, normally /third_party/sqlite shouldn't be touched at all? I'll try to find what happened...

**Comment by karolherbst** [comment]
yes, third_party libs are primary for windows builds. On Linux we are compiling only a few by our own:

cef
wxGTK-2.9.3 (because some bugs with 2.9.4)
sqlite3x (normally in no distribution)
breakpad
curl (because we need c-ares support)
