### ISSUE TITLE
cef: can't play flash videos

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#417]
desurium don't have the source to view flash videos from the official desura sources.

We need them

**Comment by Cheeseness** [comment]
My vote goes to pushing this upstream (downstream?). The only worthwhile resolution I can see is the Desura servers migrating to serve HTML5 video instead (which I think Protektor mentioned was a possibility).

**Comment by karolherbst** [comment]
see: https://github.com/lodle/Desurium/issues/136#issuecomment-5710387

**Comment by karolherbst** [comment]
It is currently a bit unstable, but I will investigate it deeper now

**Comment by karolherbst** [comment]
I found them: https://github.com/lodle/Desurium/tree/6d1adee39a76a88e5bf2b877f61a83a5b0eced51/src/third_party/npwrapper

**Comment by karolherbst** [comment]
mhh I did not delete this: https://github.com/lodle/Desurium/tree/master/third_party/npwrapper

**Comment by NothingMuchHereToSay** [comment]
Vimeo supports HTML5, but only through h.264/MPEG, so why not just kick off Flash?

**Comment by karolherbst** [comment]
h.264 is difficult, because a distributions has to pay, if they want to support this.

**Comment by karolherbst** [comment]
though it is free to use for internet applications

**Comment by NothingMuchHereToSay** [comment]
CEF/Desurium counts as an internet application though. I'm able to play HTML5 video through Desurium fine, it's just that it takes up the entire client's window. x264 is the codec that's required to play HTML5 video using h.264

**Comment by intenscia** [comment]
The player we use should default to HTML5 when flash is not supported. I will investigate why this isn't occuring

**Comment by karolherbst** [comment]
Maybe this is just an error on my side (having no x264 codes installed or cef doesn't find it).

We know, that some distributions are not having this codec in their repositories (Fedora for example).

So it would be nice to know, which codecs are supported by this meda player, maybe we can drop flash support and/or bundle some needed libs.

**Comment by intenscia** [comment]
I just deployed a change which should force HTML5 video in the client. let me know if this resolves the issue

**Comment by karolherbst** [comment]
thx I will test this later this day
