### ISSUE TITLE
Mac: CMake versions prior to 2.8.10 may fail to download external projects

### ISSUE THREAD

**Issue by ghost** [desura/Desurium#418]
The official binaries of CMake prior to 2.8.10 may fail to download files over https. This is due to the version of libcurl being linked against CMake having SSL disabled. Either the minimum required version should be increased or this bug should be documented somewhere (eg in the build instructions).

**Comment by Jookia** [comment]
CMake versions piror to 2.8.10 also don't support VS2012 so I'd say just push for it.

**Comment by karolherbst** [comment]
because it is a mac only but and because mac support is a bit away, I don't think that this will be a problem.

Setting the cmake version up to 2.8.10 will destroy compatibility with some Linux distributions. Maybe we could add a Mac only swtich like this:

```
if (APPLE)
  cmake_minimum_required(VERSION 2.8.10)
else()
  cmake_minimum_required(VERSION 2.8.5)
endif()
```

**Comment by ghost** [comment]
This is possible. Someone will have to verify that this bug does not affect Windows users however.

**Comment by karolherbst** [comment]
on windows we have problems with archive formats, but not this ssl bug

**Comment by ghost** [comment]
I can reproduce this under Windows with CMake v2.8.8.
