### ISSUE TITLE
Add an option to bundle wxgtk (at least until 3.0 got released)

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#423]
I had a little chat at #gentoo-games on freenode; it might be very reasonable to introduce an option to specifically bundle wxgtk-2.9 (whichever is the latest working version); as 2.9 is a development version it can frequently breake compatibility and people might get really upset when suddenly the new wxgtk broke desurium compilation (or functionality) and therefore could not update to a new version of wxgtk.
another proposed option was to maybe statically link it
- [x] remove wxGTK dependency from CEF
- [x] update ebuilds and PKGBUILD

**Comment by karolherbst** [comment]
wxGTK can't be statically linked, because it will lead into really big troubles. Bundling would be the way to go.

**Comment by karolherbst** [comment]
And because we don't patch wxGTK on Linux anymore, it won't conflict with the system wide installed one (if there is any)

**Comment by karolherbst** [comment]
maybe it is possible on Linux, because I tried static linking only on windows.

**Comment by karolherbst** [comment]
http://trac.wxwidgets.org/wiki/Roadmap

"Next stable release: 3.0"

**Comment by TheSiege** [comment]
if so; then please provide it as a default option, but leave the option to unbunble it

**Comment by TheSiege** [comment]
anagromataf: please test this: https://github.com/karolherbst/Desurium/commits/bug423
Works;
