### ISSUE TITLE
mcf: linking of dependencies fails?

### ISSUE THREAD

**Issue by matthiaskrgr** [desura/Desurium#428]
when I use default ./build_desura.sh script. cd into ./install/ and try to run ./mcf_extract or ./mfc_upload_cli, libs seem to be not found:

./mcf_extract: error while loading shared libraries: libmcfcore.so: cannot open shared object file: No such file or directory

./mfc_upload_cli: error while loading shared libraries: libusercore.so: cannot open shared object file: No such file or directory

Same applies for the system wide installed binaries of the PKGBUILD.

**Comment by karolherbst** [comment]
mhhh, I think we need also shell scripts like with desurium. We could also link them statically in, but yeah, I wouldn't like that. Setting LD_LIBRARY_PATH will help

**Comment by matthiaskrgr** [comment]
commit 3841d61ca89f64339e6b6d44a3a74123beabdd7b

[100%] Built target cef
Install the project...
-- Install configuration: "Release"
-- Installing: /home/matthias/vcs/github/desurium_fork_bkp/install/lib/libcef_desura.so
/home/matthias/vcs/github/desurium_fork_bkp

Now we are compiling desurium
-- using GCC
-- detected 64bit
-- Boost version: 1.52.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   thread
--   system
--   prg_exec_monitor
--   test_exec_monitor
--   unit_test_framework
-- Found libnotify: '/usr/lib/libnotify.so' and header in '/usr/include/libnotify' version => 0.7
CMake Error: File /home/matthias/vcs/github/desurium_fork_bkp/cmake/scripts/run.sh /home/matthias/vcs/github/desurium_fork_bkp/build/gen/build_out/desura does not exist.
CMake Error at cmake/modules/macros.cmake:115 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  src/executable/bootloader_lin/CMakeLists.txt:24 (install_executable)

CMake Error: File /home/matthias/vcs/github/desurium_fork_bkp/cmake/scripts/run.sh /home/matthias/vcs/github/desurium_fork_bkp/build/gen/build_out/mfc_upload_cli does not exist.
CMake Error at cmake/modules/macros.cmake:115 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  src/tools/mfc_upload_cli/CMakeLists.txt:19 (install_executable)

CMake Error: File /home/matthias/vcs/github/desurium_fork_bkp/cmake/scripts/run.sh /home/matthias/vcs/github/desurium_fork_bkp/build/gen/build_out/mcf_extract does not exist.
CMake Error at cmake/modules/macros.cmake:115 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  src/tools/mcf_extract/CMakeLists.txt:18 (install_executable)

**Comment by matthiaskrgr** [comment]
:shipit: fix confirmed
