### ISSUE TITLE
desurium windows should be closeable via ctrl+w

### ISSUE THREAD

**Issue by matthiaskrgr** [desura/Desurium#434]
I didn't find any way to close this strange console (in offline mode click on desubot, -> Console).
Esc,  ctrl+w  or ctrl+q didn't seem to work.

**Comment by karolherbst** [comment]
window can be closed by window manager (close button or rightclick => close)

**Comment by karolherbst** [comment]
we should ask before closing desurium before we implement this

**Comment by karolherbst** [comment]
as @naryl suggest the window manager should close all windows.

**Comment by matthiaskrgr** [comment]
so, should we close this issue?

**Comment by karolherbst** [comment]
are you able to close windows with your window manager?

**Comment by matthiaskrgr** [comment]
Yes, and it didn't make the entire client quit. Closing.
