### ISSUE TITLE
Build error on Arch Linux

### ISSUE THREAD

**Issue by airon90** [desura/Desurium#439]
Hi,
I uses latest Arch Linux on 64bit PC.
I tried to install desurium-git via pacaur but a build error occurred.
How can I help you?
Thank you very much for your work!

**Comment by karolherbst** [comment]
a build log would be nice

**Comment by airon90** [comment]
I can only copy the last part of the build.
Otherwise can you tell me how to do it, please? :/

**Comment by karolherbst** [comment]
maybe the last part is enough, we will see

**Comment by matthiaskrgr** [comment]
It could have happened that pacaur does the build in /tmp/  and since we compile a lot of stuff, your /tmp/ went full.

I suggest you retry with

**Comment by airon90** [comment]
Please see http://shelr.tv/records/510abb5a9660805f8d00004d even if it is not complete >:(
It's the n-th time that I retry. Sometimes the installation eats up CPU up to 100% and I have to kill my laptop and restart it.

**Comment by karolherbst** [comment]
cef will need much power to compile, even on a ivb intel cpu it will take some time to build.

**Comment by karolherbst** [comment]
But I didn't find any error so far

**Comment by karolherbst** [comment]
information about your hardware would be also nice (CPU, RAM)

**Comment by WhyNotHugo** [comment]
Build worked fine for me on ArchLinux 64, using the PKGBUILD available at https://aur.archlinux.org/packages/desurium/.
Maybe this is a hardware specific? Did you make sure you're building in a large enough partition (some AUR helpers use /tmp, and in some setups that partition is rather small).

**Comment by karolherbst** [comment]
for reference: here is the plain output http://shelr.tv/records/510abb5a9660805f8d00004d.json

**Comment by karolherbst** [comment]
I can't see any error in the output, also the error reporter is no help

**Comment by airon90** [comment]
My laptop is now broken so I can't install it no more because my actual PC is very old. Keep this issue closed by now :)
