### ISSUE TITLE
cURL version and Debian/Ubuntu

### ISSUE THREAD

**Issue by boskee** [desura/Desurium#44]
cURL needs to be updated to at least 7.21.5 as 7.21.4 won't compile on Debian/Ubuntu because of no SSLv2 support

**Comment by Jookia** [comment]
Apparently cURL in Desura is being patched to fix a multithreading DNS resolution problem. Contacting upstream and seeing if they have the fix would allow distros to use their own cURL, if the problem is fixed. I'll see what I can do there, but in the mean time it'd help if somebody (maybe even you) updated to .5.

**Comment by boskee** [comment]
Sure. I've patched cURL to 7.21.5 and c-ares to 1.7.5. Nothing seems to be broken after the upgrade.

**Comment by yurikoles** [comment]
Now curl won't build on Ubuntu. Here is solution.
http://curl.haxx.se/mail/archive-2011-12/0014.html

**Comment by Jookia** [comment]
I don't understand that solution?

**Comment by yurikoles** [comment]
Just read previous posts in that mail list thread. I got the same problem on Ubuntu.

**Comment by Jookia** [comment]
Yes, but what do I do to fix it?

**Comment by yurikoles** [comment]
Wee need to apply changes made by [that commit](https://github.com/bagder/curl/commit/2b0e09b0f98).

**Comment by Jookia** [comment]
Have you tested to see if applying the changes will work?

**Comment by Jookia** [comment]
Could you test this with the new build system?

**Comment by ssokolow** [comment]
Possibly better. A fresh clone, having followed the instructions on Ubuntu 11.10 (Oneiric), now dies with this message:

```
Linking CXX executable mfc_upload_cli
/usr/bin/ld.bfd.real: ../../../external/curl/lib/libcurl.a(asyn-ares.o): undefined reference to symbol 'ares_process_fd'
/usr/bin/ld.bfd.real: note: 'ares_process_fd' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../../lib/libcares.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../../lib/libcares.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
```

**Comment by Jookia** [comment]
Okay, if you ad -lcares to somewhere in the cmake config? (Just go to the build dir and type 'ccmake' or 'cmake-gui .') Preferably the CXXFlags.

**Comment by ssokolow** [comment]
I'm not sure I did it properly (I have no experience with cmake) but assuming I did, it didn't change anything.

Is it possible that it was already attempting to link libcares.so and the significant line is this one?

```
/usr/lib/gcc/x86_64-linux-gnu/4.6.1/../../../../lib/libcares.so: could not read symbols: Invalid operation
```

**Comment by Jookia** [comment]
I can't begin to know what's going on. Those dots look interesting, though. Do you have c-ares installed?

**Comment by ssokolow** [comment]
I've got both of these packages installed and nothing else in the `apt-cache search ares | grep ares` output looks relevant.

```
libc-ares2
libc-ares-dev
```

The dots just produce the path `/usr/lib/libcares.so` which is a symlink from `libc-ares-dev` which points to `/usr/lib/libcares.so.2.0.0` from `libc-ares2`.

**Comment by Jookia** [comment]
Hmm. I'm really not sure what the problem here is. I don't have a Debian machine to fix this. Have you tried adding c-ares to the CMake libraries in BuildCURL.cmake?

**Comment by karolherbst** [comment]
it seems, that there are problems with the installed c-ares libraries.

please try the following workaround:

cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install -DWITH_ARES=false
make

or

cd build
ccmake .. // and disable WITH_ARES there
make

this should skip the curl installation if a valild curl is found. You won't have ares support in desurium, but it should work.

**Comment by Jookia** [comment]
svenstaro (an Arch Linux package maintainer and trusted user, AKA important person) showed the the same errors occured when building the package in a controlled environment on Arch. After being annoyed at the prospect of having to download SVN repos a lot, I finally just gave in and set up a custom environment and now cURL should work.

**Comment by ssokolow** [comment]
Thanks. Seems to just work now with a bare, unadorned `./build_cmake.sh`.

That just leaves three issues:
- The instructions have become less clear about _how_ people go about copying cef out of the official build.
- If I don't want to copy cef out of the official build, where can I find instructions for building it that are up to date with this rapidly-changing build system?
- If I just want a Linux version of Desura where the Flash-based video players work, how do I build the GPL code with official Desura branding?

**Comment by Jookia** [comment]
CEF is currently broken, this is a huge problem which I'm trying to fix, and it's just goddamn horrible as I don't know how to build CEF and it's a headache. Copying CEF from the current build is not suppose to be an option.

You can't build the GPL code with official Desura branding, as it requires code that apparently is non GPL and I don't know how they're handling that legally, but the fact is that you can't compile it with official branding. Flash should work once CEF is compiled.

**Comment by ssokolow** [comment]
Flash does work in the GPLed one once I copy CEF from the official build. Hence why I wanted to replace the official build with an official-branded copy of the GPL build.

As for there still being closed-source code in the official builds:
- What does it do? (What functionality will I be losing by ditching it?)
- I was actually referring to the images when I said I wanted to build with official branding. I suppose I could just copy them from `~/opt/desura` to `~/tmp/Desurium/install` to get a Desura where the use of color in the tray icon and logo button isn't too eye-grabbing.
- I guess I'll have to prioritize switching to the GPLed build then. As with Chrome vs. Chromium, Desura isn't on my short list of allowed closed-source software. (Flash, Opera, nVidia Drivers, BIOS, $GAMES)

**Comment by Jookia** [comment]
DRM stuff is what happens. Hopefully it'll get moved serverside.

**Comment by ssokolow** [comment]
I thought the Desura client didn't yet have the infrastructure for any DRM and the GPLed version seemed to start up and run fine against my account.

What purpose does this "DRM stuff" serve?

**Comment by Jookia** [comment]
As far as I know, the only things that aren't in the source code base, is the Desura autoupdater, and Battlefield DRM stuff. You'd have to ask Lodle about it. Nothing really bad.

**Comment by ssokolow** [comment]
Ahh, so basically one component that I will hopefully soon be able to replace with an Ubuntu repository and one that probably nobody in this household would ever need to install.

That makes perfect sense and it's basically the same kind of distinction as with Chromium (lacks Chrome's auto-updater and bundled Flash and FoxIt Reader components) and Firefox (PPA builds lack the updater).
