### ISSUE TITLE
Busted .desktop file

### ISSUE THREAD

**Issue by Mailaender** [desura/Desurium#446]
The auto-generated paths

```
Exec=usr/bin/desura
TryExec=usr/bin/desura
```

won't work. As I suggested before in pull request #443 this should be simply `desura`.

The icon file is stored in `/usr/share/desurium/desura.png`, it should be `/usr/share/pixmaps/desura.png` (depreceated) or `/usr/share/icons/hicolor/256x256/apps/`. The icons in `.desktop` files should not have suffixes or paths so the desktop environment can choose whether it wants pngs or svg and which scale. I fixed this for the RPM packages on http://build.opensuse.org using:

```
mkdir %{buildroot}%{_datadir}/pixmaps
cp %{buildroot}%{_datadir}/desurium/desura.png %{buildroot}%{_datadir}/pixmaps
```

```
desktop-file-edit --add-category="Amusement" \
                  --set-key="Exec" --set-value="desura" \
                  --set-key="TryExec" --set-value="desura" \
                  --set-icon="desura" \
                  --set-generic-name="Digital games distribution client" \
                  %{buildroot}%{_datadir}/applications/desura.desktop
```

This huge manipulation to get the build not rejected requires http://freedesktop.org/wiki/Software/desktop-file-utils >= 0.19.

**Comment by karolherbst** [comment]
I think we should add some overrides. If cmake was configured with absolute paths, everything will be all right.

It isn't that easy to find a mechanism, that will fit to everyone needs, so either we should delete this file at all (doesn't make sense because of #445).

We could also add an option, where you can say "yes desurium is in path and the icon file is stored in pixmaps or hicolor".

**Comment by Mailaender** [comment]
It would be great if the above are the default values, so Fedora only needs to add the `Vendor=` field and openSUSE only needs to add a subcategory. Not sure how this could break other distributions. The icon should be placed in `/usr/share/icons/hicolor/256x256/apps/` not with a switch to pixmaps as this folder should go away soon.

**Comment by karolherbst** [comment]
I think every distributions should install the icons as they want.

We have a svg file of desubot under C0.

**Comment by Mailaender** [comment]
Let's not complicate things then. Works for me™ now.
