### ISSUE TITLE
desura crash since #485

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#459]
/usr/games/lib64/desura/desura: symbol lookup error: /usr/games/lib64/desura/libdesura_flashwrapper.so: undefined symbol: g_strdup_printf

then crash

adding glib-2.0 to set(PLATFORM_LIBS dl) doesn't fix it

**Comment by karolherbst** [comment]
this should be added to the desura_flashwrapper target

**Comment by TheSiege** [comment]
yes I added that to third_party/npwrapper/CMakeLists.txt or somwhere specific in there?

**Comment by karolherbst** [comment]
[third_party/npwrapper/CMakeLists.txt#L39-41](../blob/master/third_party/npwrapper/CMakeLists.txt#L39-41)

**Comment by karolherbst** [comment]
btw, this ${SQLITE_LIBRARIES} is wrong there...

**Comment by TheSiege** [comment]
adding it there finally fixes it

**Comment by karolherbst** [comment]
mhh okay
