### ISSUE TITLE
Can't build in Fedora 16 and Debian Wheezy.

### ISSUE THREAD

**Issue by NothingMuchHereToSay** [desura/Desurium#460]
http://pastebin.com/TNKMNEmX

That's the error that occurs. I assumed it was Flash player that needed to be installed but that didn't help either.

**Comment by karolherbst** [comment]
You have to install libxt-dev or something similiar

**Comment by karolherbst** [comment]
is the issue fixed with installing the dev files for this library?

**Comment by karolherbst** [comment]
closed because @NothingMuchHereToSay said so
