### ISSUE TITLE
move to tinyxml-2

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#491]
from http://www.grinninglizard.com/tinyxml2/index.html:

TinyXML-1 or TinyXML-2?

Both parsers:
- Simple to use with similar APIs.
- DOM based parser.
- UTF-8 Unicode support. http://en.wikipedia.org/wiki/UTF-8

Advantages of TinyXML-2:
- The focus of all future dev.
- Many fewer memory allocation (1/10th to 1/100th), uses less memory (about 40% of TinyXML-1), and faster (~5x on read).
- No STL requirement.
- More modern C++, including a proper namespace.
- Proper and useful handling of whitespace

Advantages of TinyXML-1
- Can report the location of parsing errors.
- Support for some C++ STL conventions: streams and strings
- Very mature and well debugged code base.

I think tinyxml-2 should be a nice performance win for desurium, because it will speed up
- game syncing
- localisation loading
- other xml based operations

**Comment by Smilex** [comment]
I'm just noting that I'm a bit interested in doing this one since I've used tinyxml-2 a couple of times. 
So I wanted to ask, is anybody working on this?

**Comment by Jookia** [comment]
I don't think so. Any help is appreciated though!

**Comment by karolherbst** [comment]
no, I'm not. And because it is targeted for 1.0 we will have this a long time in master for testing and stuff. So no hurry at all :)

**Comment by Smilex** [comment]
I'm writing stuff here temporarily that I want to run by others.
Line 138 | tools/mcf_utils/code/SaveMCF.cpp -- Loads XML file and then saves it at same location. Does noting in between

lodle: it formats the xml to be pretty :D

Line 80 & 93 & 106 & 119 | include/XMLMacros.h -- The fuck? No idea what the purpose with !!child is

lodle: !!child is a warning free way of converting pointer to bool.

**Comment by karolherbst** [comment]
yeah, I think these lines can be removed

**Comment by TheSiege** [comment]
regarding tinyxml2; it feels like resizing is a little faster now; also syncing the game library went down from 2.5minutes to 1.5minutes

**Comment by LiamDawe** [comment]
I would call that major progress!

**Comment by karolherbst** [comment]
I am worried about this resizing speedup. What happens while resizing at all? Maybe there is some strange stuff going on.

**Comment by lodle** [comment]
How many games do you have slege?

**Comment by karolherbst** [comment]
what is more important: he has a very fast internet connection, so the transfer rate isn't the bottleneck here, but I think he has around 100, maybe more

**Comment by lodle** [comment]
shouldnt take 1.5 mins to sync.

**Comment by karolherbst** [comment]
yeah, I noticed, that it is much faster on windows than on Linux, maybe I am wrong, but it depends on how many games you have installed (at least for me it did)
