### ISSUE TITLE
Building Desura/Cefs on Linux can be automated

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#5]
Considering the readme just tells you to write in commands, it seems simpler to wrap them in a shell script and have the user use that does it not?

**Comment by lodle** [comment]
well this is true, but easier to know the parts and how to build them by hand. Once setup all that is needed is to run build.sh from build_lin

**Comment by Jookia** [comment]
True, but most people who build from source usually unzip the sources and run 'make', so all these instructions can seem unfriendly, especially if there's no reason the user is forced to follow them when it could be in a script. Also, BuildAll breaks as it tries to Build Cefs without the user's input.

There's lots of good reasons to learn how to build Desura by hand, but it shouldn't be _required_ as it'll just upset people who want to build it overnight.

**Comment by lodle** [comment]
true, BuildCef.sh should be removed from it. Ill look into making a make file that can do all the steps in one

**Comment by Jookia** [comment]
This is implicitly fixed with CMake.
