### ISSUE TITLE
doubled german entries in language selection

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#503]
in contrast to what is stated, the language option German is not german but english, but the option German(1) is german

**Comment by karolherbst** [comment]
the problem should be somewhere in this method: https://github.com/lodle/Desurium/blob/master/src/shared/uicore/code/gcJSSettings.cpp#L123

**Comment by karolherbst** [comment]
fixed in d3e1e99f28ae78d00df51c88d11a6ddcb026cb86
