### ISSUE TITLE
dual license desurium to BSD+GPLv3

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#509]
Desura Pty Ltd. wants desurium to be dual license under BSD and GPLv3. The BSD clause should be only valid for desura ltd. and GPLv3 for anybody else.

@matthiaskrgr @makson96 @jcnix @harmonise @boskee @Smilex @sadam36 @Cheeseness @yurikoles @TheSiege @LarryRotgut @cerebrux @AllenWalkerHU @naryl @Telemaniaka @madrang and @ssokolow you have contributed to desurium and so we need your thoughts on that.

agrees:
- Cheeseness
- Jookia
- makson96
- yurikoles

wants other license:
- Cheeseness
- karolherbst
- makson96
- ssokolow
- TheSiege

does not care:
- harmonise
- jcnix
- matthiaskrgr
- Telemaniaka

no answers yet:
- boskee
- Smilex
- sadam36 
- LarryRotgut
- cerebrux 
- AllenWalkerHU 
- madrang

**Comment by karolherbst** [comment]
@LarryRotgut @cerebrux @AllenWalkerHU @naryl @Telemaniaka @madrang and @ssokolow 
some of the names weren't linked above

**Comment by Jookia** [comment]
I think due to the sheer amount of work they've done on it (99% or so) they should be allowed to dual license.

But can we justify a dual license? Why is the GPLv3 not good enough for Desura Ltd? Could this lead to in-house development being forked back?

**Comment by karolherbst** [comment]
a BSD license would allow desura to not publish changes to desurium with GPL they have to.

**Comment by Jookia** [comment]
Well, yeah. But why are we open source then?

**Comment by karolherbst** [comment]
To help developing. But you are right, I don't see any good reason why we should not stay GPLv3 only.

**Comment by ssokolow** [comment]
I could imagine a case for licensing under the LGPL or even the MPL to gain compatibility with other licenses, but I can't see any justifiable case for removing the copyleft protection on the existing code.

If nothing else, dual-licensing to BSD would be a horrible PR move as various people would see it as a betrayal and, when it comes to the human psyche, there's a reason Dante's Inferno reserved the lowest circle of hell for betrayers.

**Comment by jcnix** [comment]
At least for my part, it doesn't matter to me.  You can make my patches public domain or proprietary for all I care.

**Comment by TheSiege** [comment]
I do agree with @ssokolow LGPL should be good enough, from what I know we are talking about some updater code and that should then be covered

**Comment by karolherbst** [comment]
@ssokolow: a change to LGPL would mean, that we have to create some plugin architecture, so that desura can create their own "modules". If we don't have something like that, LGPL won't have any effect

**Comment by Jookia** [comment]
I've already signed a CLA, so whatever happens Desura can use my changes. However, I have a feeling its up to Karolherbst with the massive amount of work he's done.

**Comment by ssokolow** [comment]
@karolherbst: As far as I remember, it just means that the proprietary stuff has to be compiled into a separate `.dll`, `.so`, or `.dylib` with a defined enough ABI that they can be swapped out... though I can see why you might call that a plugin API.

Are you familiar with the MPL? From what I understand, it defines some kind of per-file copyleft and the MPL 2.0 is explicitly compatible with the LGPL and other GPL-family licenses.

**Comment by Cheeseness** [comment]
From what I understand, we still don't have a firm stance from the Desura guys (Protektor's comments came across as a suggestion of what he felt the simplest option was).

Personally, I have no problem with the contributions I've made so far being dual licenced under those mentioned, but I would much prefer to see, and believe the project would be more likely to flourish as a single licenced project (there are other options for allowing the client to execute proprietary code which could potentially meet Desura's needs).

For clarity, a couple of items, such as CD key stuff were removed from the client when it was open soruced ( @Jookia can talk more to this), and the Desura guys want to feel able to put that stuff back in as well as any future things that might come up. It was apparently their intention to have the project dual licenced from the beginning, but that wasn't communicated here on GitHub, and so we can't assume that any of our contributors have agreed to it until we have explicit permission.

**Comment by makson96** [comment]
Maybe it is good time to ask Desura guys to put some paid workforce into opensource Desurium for exchange of changing license?

**Comment by ssokolow** [comment]
Regarding my previous message, I just checked. Here's Wikipedia's description of how the MPL works:

> The MPL has been approved as both a free software license (albeit one with a weak copyleft) by the Free Software Foundation[3] and an open-source software license by the Open Source Initiative.[4] The MPL allows covered source code to be mixed with other files under a different, even proprietary license. However, code files licensed under the MPL must remain under the MPL and freely available in source form.[5] This makes the MPL a compromise between the MIT or BSD licenses, which permit all derived works to be relicensed as proprietary, and the GPL, which requires the whole of a derived work, even new components, to remain under the GPL.
> 
> -- https://en.wikipedia.org/wiki/Mozilla_Public_License

...and here's the relevant summary of the MPL 2.0's compatibility:

> **What makes the MPL 2 different from MPL 1.1?**
> 
> These bullet points are intended to summarise what is distinct about the MPL v2. They are not intended as a full description of its features. In comparison with the Mozilla Public License v1.1, the Mozilla Public License v2:
> - amended conditions around patent licence termination, making it compatible with the Apache Software License v2
> - introduces compatibility with the GNU GPLv2, GNU LGPL v2.1, GNU Affero GPL v3 and all subsequent versions of those licences
> - is simpler and shorter
> 
> -- http://www.oss-watch.ac.uk/resources/mpl2

**Comment by Cheeseness** [comment]
@makson96 Ha, that's an awesome idea, but I think that it'd be very important to steer clear of anything that allowed the perception that we'd bargained/traded away licencing.

**Comment by Jookia** [comment]
To my knowledge some Battlefield DRM and an auto updater which were proprietary were removed due to the GPL. If there was a dual license intended from the beginning, there's been poor communication and it would make the selection of the GPL 'mistaken'.

I'd like to iterate that I personally don't support dual licensing. To me it implies that we've made a mistake in license selection and that we should be able to find an intermediate license that supports both the FOSS side and Desura's side, or that somebody wants the benefits of open source, without the open source.

We could always opt for something like the Apache license, much like Chromium does, which Google takes and repackages to be Google Chrome.

**Comment by ssokolow** [comment]
@Jookia The problem is that the Apache license is, in effect, a BSD license with a patent-granting clause (and quirks that make it incompatible with pre-3.0 versions of the GPL, but that's not relevant here).

The reason I suggested the MPL 2.0 is because it it's specifically designed to be a compromise between BSD and GPL, requiring MPL-licensed files to stay open-source, but allowing you to link in files under other licenses and build closed-source programs as long as the source is provided for any modifications to the MPL-licensed files.

**Comment by Cheeseness** [comment]
@Jookia There's stuff in the Desura forums talking about dual licencing since before the initial code review (starting with the [first post](http://www.desura.com/groups/desura/forum/thread/open-sourcing-desura) in this Open Sourcing Desura thread).

**Comment by ghost** [comment]
I'm fine with pretty much any licence.

On Fri, Mar 8, 2013 at 12:07 PM, Cheeseness notifications@github.comwrote:

> @Jookia https://github.com/Jookia There's stuff in the Desura forums
> talking about dual licencing since before the initial code review (starting
> with the first posthttp://www.desura.com/groups/desura/forum/thread/open-sourcing-desurain this Open Sourcing Desura thread).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lodle/Desurium/issues/509#issuecomment-14596999
> .

## 

--Daniel Maloney

**Comment by karolherbst** [comment]
I think the best Option would be LGPL.
1. Because desura does not want to change functionality, but wants to add it.
2. It would fit better with officials releases, because libs can be exchanged without harm.
3. Any change to the code base of desura will help desurium as well.

I don't see any reason why BSD is required, there is no problem with developing a simple plugin architecture.
Imagine we would create a plugin API for updater. Then it would be possible to make distro specific stuff, like update over apt or other package managers.

**Comment by makson96** [comment]
I too agree that LGPL is safe for everyone. But we should hear from Desura if it fit their needs.

I agree to change license and I speak also in the name of @tomaszmakarewicz because I am him (just for mistake committed from university account).

What if all committeres will not speak in this subject? Than we will not be able to change license?

And as I already said this is good opportunity to ask Desura for something in return. One full time developer is all we can dream about. And he would be as important for Desura as for us.

**Comment by Cheeseness** [comment]
Whilst I think it'd be fantastic if Desura had a paid developer working on the client, I think we should be talking about that separately from this issue.

If we're going to ask contributors to agree to re-licence their work, then that needs to be done on its own merits, not in exchange for anything.

We had previously talked about excising code from anybody who wasn't previously happy with a licence change (though I doubt we could find anybody who would give up their time to do that, nor do I think we could raise enthusiasm to get anybody to write replacement code).

**Comment by Telemaniaka** [comment]
I don't feel confident enough in my knowledge on the matter to make an educated contribution to the discussion, and my patches are insignificant. I'll agree to whatever you guys decide.

**Comment by matthiaskrgr** [comment]
Mh, I'm not sure if I care a lot about this :|

**Comment by karolherbst** [comment]
any other minds about that topic?

I miss comments from @boskee @Smilex @sadam36 @yurikoles @LarryRotgut @cerebrux @AllenWalkerHU @naryl and @madrang

**Comment by naryl** [comment]
I didn't contribute directly to desurium codebase. But if you still want my opinion I need to know what problems are they trying to solve first. Maybe there's a better way.

**Comment by Jookia** [comment]
That's a good point.

**Comment by karolherbst** [comment]
So can I summarize the result to:
Most would agree, but we want to know why GPL isn't enough and why we can not use LGPL/MPL

**Comment by ssokolow** [comment]
@karolherbst I have no problem with that summary.

**Comment by makson96** [comment]
Me 2

**Comment by yurikoles** [comment]
I signed CLA before any pull requests.
Maybe Desura Pty Ltd. have to ask all contributors to sign CLA?

**Comment by karolherbst** [comment]
I don't know if everybody is happy with that. Especially now after ubuntu was pissing on wayland and CLA+GPL has gotten even more unpopular

**Comment by Cheeseness** [comment]
I threw pretty much the same summary out to the Desura guys about a week ago. There are other ways of doing the things that have been raised so far, and we're still waiting to hear a solid response on where Desura wants to take this.

I don't know if I'm interested in signing anything to be honest.

**Comment by karolherbst** [comment]
Me neither.

My current plan is to create a wiki page about all copyright and license stuff. I would suggest to put little contributions into public domain if the copyright holder just don't care (like the FSF is suggesting this).

**Comment by Cheeseness** [comment]
I think we should definitely hold off on that sort of thing until we have a firm resolution and path through this though.

**Comment by karolherbst** [comment]
desura wants to figure out how much time it would take to move the drm stuff on the server side. Regardless to this we should think about #538 and decide which parts of the client should be LGPL, so that games could link against the desurium plugin API.

I would change the license to LGPL of these libs:
- util
- util_fs
- util_thread
- ipc_pipe

**Comment by karolherbst** [comment]
guys involved in these libs are @boskee @jcnix @Jookia @karolherbst @lodle @matthiaskrgr and @Smilex

**Comment by karolherbst** [comment]
After this topic is finished, I think we should add copyright information like it is done in wine: https://github.com/mirrors/wine/blob/master/dlls/wined3d/texture.c

**Comment by karolherbst** [comment]
things changed now, I want to close this issue until things cleared up and so on

**Comment by karolherbst** [comment]
not a topic anymore
