### ISSUE TITLE
split repositories desurium <-> desurium-cef

### ISSUE THREAD

**Issue by hasufell** [desura/Desurium#514]
Splitting out the desurium-cef part to a seperate repository has a few advantages for the user.

When using the repositories directly for building desurium and desurium-cef one can't really tell when it's necessary to update both of them or just one.

Gentoo for example has tools that check the repositories of live ebuilds for new commits and will trigger a rebuild of those packages.
That means whenver you change anything in your main repository one would rebuild both desurium and desurium-cef even though the changes might not be related to desurium-cef at all.
The same goes for the regular user who would probably just jump on github and check for new commits, but can't exactly tell what they are related to.

**Comment by makson96** [comment]
I think that the target here is to use mainstream cef without additional patches. If this will be accomplished, there will be no need to recompile cef, as one can always use system installation of libcef.

The other issue is that most distribution do not provide libcef in their repository and we should probably encourage them to do so.

I wonder if one can modify Chromium build process (provided by repositories), so the additional, optional package with libcef library will be created?

**Comment by karolherbst** [comment]
there are two packages for CEF:
1. chromium sources
2. Cef sources

the bigger problem is that while I try splitting the build process of cef_desura into cef and cef_desura (so we would have libcef.so and libcef_desura.so linked against libcef.so) I ran into link errors. Maybe I will fix all these errors the next weeks.
