### ISSUE TITLE
desura:// links don't work from external browser if client is already opened

### ISSUE THREAD

**Issue by Mailaender** [desura/Desurium#515]
I can reproduce it with Firefox 19.0.0.2 and Desurium RC 9:
1. Fire up Desurium
2. Go to http://www.desura.com/games/openra
3. Click http://www.desura.com/games/openra/play
4. Click desura://launch/games/openra
5. Choose "Start application: Desura"

`Desurium is already running, If it's not, remove "~/.desura/cache/applock".`

It should execute the action without requiring the client to be not already running.

**Comment by Mailaender** [comment]
This might be a KDE and xdg-utils issue:

```
(2891, son of 2890) /home/abuild/rpmbuild/BUILD/Desurium-0.8.0_rc9/src/static/util/code/UtilLinux.cpp:480 - launchProcessXDG
(2989, son of 2891) /home/abuild/rpmbuild/BUILD/Desurium-0.8.0_rc9/src/static/util/code/UtilLinux.cpp:511 - Launching with xdg-open
(2989, son of 2891) /home/abuild/rpmbuild/BUILD/Desurium-0.8.0_rc9/src/static/util/code/UtilLinux.cpp:514 - Must have failed. Launching with gnome-open
```

xdg-open is installed, but not gnome-open.

**Comment by karolherbst** [comment]
"desura://" has to be registered to desurium
https://github.com/lodle/Desurium/blob/master/cmake/scripts/desura.desktop#L10

You could also take a look on #518. I think with these changes the desktop file can be installed without any harm

**Comment by Mailaender** [comment]
This is how the .desktop file currently looks like:

```
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Name=Desurium
GenericName=Digital games distribution client
Type=Application
Comment=Free software version of Desura game client
Exec=desura
TryExec=desura
MimeType=x-scheme-handler/desura;
Icon=desura
Terminal=false
Categories=Game;Amusement;
StartupNotify=false
X-Desktop-File-Install-Version=0.21
```

It is however heavily edited during RPM installation:

```
desktop-file-edit --add-category="Amusement" \
                  --set-key="Exec" --set-value="desura" \
                  --set-key="TryExec" --set-value="desura" \
                  --set-icon="desura" \
                  --set-generic-name="Digital games distribution client" \
                  %{buildroot}%{_datadir}/applications/desura.desktop
```

Maybe I just forgot to update the MIME database on %postinst. Will have a look.

**Comment by karolherbst** [comment]
with #518 you don't need to modify the generated desktop heavily file anymore.

Just use both cmake options: DESKTOP_EXE (will set Exec and TryExec) and DESKTOP_ICON (will set Icon)

**Comment by Mailaender** [comment]
https://build.opensuse.org/request/show/160167 might fix it.

**Comment by karolherbst** [comment]
would make sense

**Comment by Mailaender** [comment]
Nope, did not fix it. Desurium does not do any action and shows this pop-up when it is already running.

**Comment by Mailaender** [comment]
How to reproduce:
- paste desura://install/games/project-zomboid/523 into a browser of your choice
- Firefox/Chrome will warn you that an external application will be started.
- Desurium is started up or shows `Desurium is already running, If it's not, remove "~/.desura/cache/applock".` but only opens http://www.desura.com/games/ instead of doing anything.

**Comment by karolherbst** [comment]
strange, executing "desura desura://install/games/project-zomboid/523" will result into the same message, but it will launch the game

**Comment by Mailaender** [comment]
Well at least we know it is an unknown packaging bug on my side and not a bug in Desurium.

**Comment by karolherbst** [comment]
it is a desurium bug, because this will fix this with xdg-open: https://github.com/karolherbst/Desurium/commit/fe065f8c8254069977af063c5287b58a040b4986

**Comment by karolherbst** [comment]
but the error mesage is still appearing

**Comment by Mailaender** [comment]
Maybe just hide it as a legitimate debug warning and don't have it pop-up to annoy the user.
