### ISSUE TITLE
mcf_upload_cli needs -DCMAKE_EXE_LINKER_FLAGS=-ldl

### ISSUE THREAD

**Issue by ienorand** [desura/Desurium#525]
When compiling mcf_upload_cli, manually adding
    -DCMAKE_EXE_LINKER_FLAGS=-ldl
was needed, this should be set in cmake?

**Comment by karolherbst** [comment]
could you provide more information about this? It never occured to me. CMake and build output will be very helpful

**Comment by karolherbst** [comment]
because we will remove this tool in the future and the issuer never answered, I close this
