### ISSUE TITLE
can't download sources with low-speed connection.

### ISSUE THREAD

**Issue by matthiaskrgr** [desura/Desurium#540]
I don't seem to be able to download sources with a 10 kb/s connection.

Compiling cef...
-- using GCC
-- Detected 64bit
-- Working multilib, enable 32bit support
-- the value of env CFLAGS: 
-- the value of env CXXFLAGS: 
-- the value of env LDFLAGS: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matthias/vcs/github/desurium_fork_bkp/build_cef
[  2%] Performing download step (download, verify and extract) for 'chromium'
-- downloading...
     src='http://commondatastorage.googleapis.com/chromium-browser-official/chromium-15.0.876.0.tar.bz2'
     dst='/home/matthias/vcs/github/desurium_fork_bkp/build_cef/chromium-prefix/src/chromium-15.0.876.0.tar.bz2'
     timeout='none'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]

The download seems to just stop, (no more progress) but the build does not fail.
Additionally when I ctrl+c and restart the compilation the file is REMOVED and downloaded AGAIN FROM THE BEGINNING! We should just RESUME the download and not RESTART it.

**Comment by Mailaender** [comment]
I suggest you use http://openbuildservice.org/2013/04/30/version-2.4/ which has PKGBUILD support now.

**Comment by karolherbst** [comment]
I don't think we can do much herem because connection slow like that are mostly EDGE connections these days. They aren't very stable anyway and errors in the connection are quite normal.

Anyway this isn't a problem desurium can or should take care of, because we are using a cmake module for this named "ExternalProject". We could open an issue there.
