### ISSUE TITLE
where should archvies for building desurium be stored?

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#544]
we can't upload new files on github so we have to search for another download server.

The uploaded archives are broken for windows, so we have to find a solution for that fast.

**Comment by makson96** [comment]
There are plenty of such a solutions. Google Drive might be considered. http://thebiobucket.blogspot.com/2011/10/how-to-link-to-google-docs-for-download.html

But maybe one can ask Desura, if they don't want to spare some space on their servers for this. It would make it more official :)

**Comment by TheSiege** [comment]
sourceforge; maybe even dropbox ...

**Comment by TheSiege** [comment]
https://sourceforge.net/projects/desurium/files/

**Comment by TheSiege** [comment]
http://pastebin.com/FmPVS3Un

**Comment by karolherbst** [comment]
urls are working for me
