### ISSUE TITLE
Can't get desura or desurium to log in... 

### ISSUE THREAD

**Issue by Chris-Franklin-1701** [desura/Desurium#545]
I have downloaded Desura and Desurium 5 times each now. I have installed and updated them just fine, but when I try and log in with the account I made, it will not walk in. I get an error:

(https://secure.desura.com/3/memberlogin)
[SSL connection timeout][58.28]

Any help would be appreciated. Thank you!

**Comment by karolherbst** [comment]
What version of curl is installed on your system and with what SSL backend? ("curl -v" should be the command)

**Comment by Chris-Franklin-1701** [comment]
curl is the latest version.  When I do "curl -v" in terminal, it states "No URL specified".

**Comment by karolherbst** [comment]
sorry for that, the command is "curl --version"

**Comment by Chris-Franklin-1701** [comment]
curl 7.29.0

**Comment by karolherbst** [comment]
I wanted the full output (because the curl configuration depends on more than just the version)

I got this output:

```
curl 7.30.0 (x86_64-pc-linux-gnu) libcurl/7.30.0 OpenSSL/1.0.1e zlib/1.2.7 c-ares/1.9.1 libidn/1.26 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by Chris-Franklin-1701** [comment]
I did a fresh install of 13.04, and now desura works.  Thank you for the help!
