### ISSUE TITLE
Desura icon in gpl build

### ISSUE THREAD

**Issue by boskee** [desura/Desurium#55]
The main menu button in gpl build is still using Desura's icon.

**Comment by Protektor-Desura** [comment]
Yes, my understanding is that as long as you don't make any changes to the official client then you can use the name and the logos. If you change the code then it isn't Desura any more and can't use the name or logos, just like Firefox does.

**Comment by boskee** [comment]
I was actually thinking about providing a logo for Desurium. My sister is a graphic designer specialising in branding, so she could make one. Problem is that I don't even know if you are looking for a logo.

**Comment by Protektor-Desura** [comment]
Send one on over it can't hurt. If they decide the want a different logo for the open source one then it is there ready to go.

**Comment by madrang** [comment]
If the artwork is to be released under Creative Commons then we could also do a contest at http://opengameart.org/ and then the best logo/theme could be used. Also i think CC-By-Sa would be the best license for the artwork.

**Comment by Protektor-Desura** [comment]
I agree that I think that would probably be the best license for a logo/branding/whatever. You should ask lodle about the contest since that is a bit more his area than mine.

**Comment by Jookia** [comment]
I've moved this to the branding bug.
