### ISSUE TITLE
Password length problem

### ISSUE THREAD

**Issue by Plak** [desura/Desurium#559]
Hi,

there seems to be a problem with the password length.
I am usually using a password with a length of over 25.
I can log into the website with that password without any issues.
I can not log into the desurium client with a password that long.
I do get an "wrong password" error.

desurium version 2:0.8.0~rc9-0ubuntu1makson1 from http://ppa.launchpad.net/makson96/desurium-stable/ubuntu

Best regards,
Plak

**Comment by Jookia** [comment]
From what I can tell this may be an API problem:

WebCoreClass::logIn has a correct password parameter and posts it to the server, using webCoreClass::postToServer. However, it fails when looking for the 'member' element.

Unless there's a flaw somewhere here, it looks to be a server-side problem. Can I summon @intenscia ?

**Comment by Jookia** [comment]
Just after writing that it seemed to be magically fixed, with no code intervention? Can anybody confirm this?

**Comment by karolherbst** [comment]
works for me on windows, too

**Comment by Jookia** [comment]
I'm assuming this was a backend problem with client APIs.
