### ISSUE TITLE
Add an option to have v8 as built-in library on Linux

### ISSUE THREAD

**Issue by akien-mga** [desura/Desurium#567]
It would be nice to be able to build v8 during the compilation of Desurium, if v8 could not be found by CMake during the configuration, just like wxWidgets or cURL are built if need be.

To allow the packaging of Desurium on a system which does not provide v8, it should also be possible to build v8 from a local tarball and not only from SVN (the location or URL of the tarball being specified by something like V8_URL passed as an argument to cmake).

**Comment by karolherbst** [comment]
@akien-mageia it could be, that these changes I made won't be merged in the near future. The v8 build system is a bit messy and I have to rely on things which aren't the same on win32 or Mac OS X. Nethertheless I will make a patch ready which can be used by people who want to use it, so I will create a branch for this here and not only in my private repository.

I hope I can finish this today, so you can use it :)

**Comment by karolherbst** [comment]
take a look on this: https://github.com/karolherbst/Desurium/compare/5902c0679a31504e0f7f733a619fda031d8666ed...c1764753017c28145ae3ab0b752db82ac03a0b11

It should work, but I did not cleaned it up and I want to finish it for max os x/win32, too

**Comment by akien-mga** [comment]
Thanks Karol!

I produced a patch for the release tag 0.8.0_rc10 based on your diff, and it works. I now have a working RPM to install Desurium on Mageia, but I still have some work to do on it (such as updating c-ares and have the system curl built with it, to reduce the number of build-in libraries in Desurium).

I don't close the ticket, since you said you want to clean it up and work on it for Mac OSX and Windows.

**Comment by karolherbst** [comment]
thanks for your respond, I'm happy that it is working for you :)

**Comment by karolherbst** [comment]
I don't know why, but we got only problems with c-ares on ubuntu see here #199 
It might be, that it will run fine without it, I am not sure, because I never figured out what is causing the crash at all.
