### ISSUE TITLE
some theming issues

### ISSUE THREAD

**Issue by ghost** [desura/Desurium#568]
There is a white border in the breadcrumb.
The about dialog does not fit.
The reload button is scaled.

Theme:  http://sixsixfive.deviantart.com/art/Desura-simpliX-346609950

The theme works in the official client but fails in Desurium

![2013-06-23-123838_1366x768_scrot](https://f.cloud.github.com/assets/3780774/692051/86ab5cc4-dbf1-11e2-9f64-fc8daef70b7b.png)

![2013-06-23-123505_1366x768_scrot](https://f.cloud.github.com/assets/3780774/692052/8cee7d6e-dbf1-11e2-87ad-d42bb98380ae.png)

**Comment by karolherbst** [comment]
Thanks for reporting. The reload button might be the cause of this breadcrumb issue we discovered before (#213). This "white blank" might come from a previous commit I made, because the text area was to small on some systems. I try to get a patch ready until Wednesday

**Comment by karolherbst** [comment]
We are closing this, because the other issues you mentioned are already covered by other issues
