### ISSUE TITLE
Linden Lab wants to by/bought desura

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#571]
we should get information what they want to do with desurium and try to get one for them in the desura IRC channel.

**Comment by Jookia** [comment]
Can we get some more sources on this? Right now all I've heard is from http://techcrunch.com/2013/07/10/second-life-maker-linden-lab-buys-desura-for-games-distribution-plans-to-keep-it-open/ . I don't know of any citations, or if Linden Lab does actually plan on keeping it open. On top of that, are we sure this isn't a rumor?

From what I know (this is all off the top of my head) Linden Lab is friendly with free software, even having their Second Life client open (I think GPL'ed), so I'm fine with this (not that I have any say, but I'm not going to go anywhere if this happens)

karolherbst is the main Desurium developer at the moment, so he probably has the most leverage over licensing issues, as his contributions are the difference between Linden using the initial FOSS release and Desurium. Unless he's signed a CLA?

I think this would be great for the project in the long term if it means more developers.

**Comment by TheSiege** [comment]
http://www.lindenlab.com/releases/linden-lab-acquires-desura
doesn't get more official than that

**Comment by Jookia** [comment]
Interesting. There's nothing about keeping it open, just continuing the service. Does this mean kicking all the existing developers off and taking control of the GitHub page now that we're all on Desura's account? Does it mean we'll have new developers arriving? Does it mean nothing will change?

**Comment by intenscia** [comment]
This is official, I have just posted the news here: http://www.desura.com/news/linden-lab-acquires-desura

Rest assured Desura will remain open. In fact Linden wants to invest in the service, grow it and really start working to make it better for our community and developers. For a while our small team has been quite limited, and not able to push out updates and ideas as quickly as we like. The addition of resources and support from Linden will allow us to return to our roots of innovating and experimenting. I'm very excited.

**Comment by karolherbst** [comment]
As I mentioned earlier: we shouldn't diverge the desura and the desurium code base at all.

There are is already some infrastructure done within the build system to do something like this. All non GPL stuff (as long as this is really needed) can be moved out into externel runtime loaded libraries.

I will be not available after Friday until End of July for desurium, because of vacation. Maybe I will have internet access, but I won't be able to do anything.

**Comment by Jookia** [comment]
If it helps I'm usually around with management and happy to organize or answer questions, although not on behalf of karolherbst's opinions.

I do think we should push to have the code base entirely GPL, and evaluate if we really really need proprietary functions before we do a plugin system.

**Comment by karolherbst** [comment]
I found out, that it is required to sign a CLA for second live: http://lecs.opensource.secondlife.com/SLVcontribution_agmt.pdf

So we have to make clear how this will effect desurium

**Comment by Cheeseness** [comment]
That doesn't automatically apply to Desurium. We're going to need to wait for further communication to get a picture of what (if any) impact this is going to have for us.

I was hoping we'd have licencing/rights stuff well and truly resolved before anything like this happened, but alas, it wasn't to happen.

**Comment by lodle** [comment]
Hey All, 

When I work out whats going on with Desura ill let you know. At the moment we aim to be working from the git branch and pushing back to it as well.

Mark

**Comment by Jookia** [comment]
Are you back on the team Lodle? :o

Edit: IRC says yes.

**Comment by oz-linden** [comment]
http://www.desura.com/news/desuradesurium-open-source-direction

**Comment by karolherbst** [comment]
I think we can close this thread, because important stuff is either clarified or in other issues
