### ISSUE TITLE
Upcoming Games - Release date

### ISSUE THREAD

**Issue by makson96** [desura/Desurium#577]
As you can see on the picture, something is wrong with displaying release dates of the games:
https://imageshack.us/a/img163/7018/eztl.png
It says:
"Dominions 4: Thrones of Ascension - Available in {0} 28 {0} days {1} hour."
So those zeros and brackets seems to be some kind of malfunction.

**Comment by lodle** [comment]
The {0} are place holders for content. Looks like your language file is out of date or incorrect. Try with English?

**Comment by makson96** [comment]
Yep, in English it looks fine. I will tweak translation files than and look for the solution and propose patch.

**Comment by karolherbst** [comment]
thanks a lot :)
