### ISSUE TITLE
mcf_upload_cli does nothing 

### ISSUE THREAD

**Issue by Mailaender** [desura/Desurium#579]
I tried **mcf_upload_cli -u myusername -p mypassword -f /home/matthias/Projekte/OpenRA/packaging/linux/root/usr/share/openra/ -i 14718 -t games** and it does just nothing. No response that it aborted or completed. I guess it failed because it exits too fast and http://www.desura.com/games/publish/openra/execute stays empty. Unsure how to investigate and fix this also in regard of #550.

---
##  MCF Upload Utility By @Lodle

Usage:
        --username (-u): Desura Username
        --password (-p): Desura Password
        --folder (-f): Folder of game files
        --item (-i): Item site area id
        --type (-t): Item site area (mods | games)

**Comment by karolherbst** [comment]
I think lodle will maybe work on this, moving to 0.8 milestone

**Comment by lodle** [comment]
Please provide linux version and gcc versions.

**Comment by Mailaender** [comment]
```
Linux version 3.7.10-1.16-desktop (geeko@buildhost) (gcc version 4.7.2 20130108 [gcc-4_7-branch revision 195012] (SUSE Linux) ) #1 SMP PREEMPT Fri May 31 20:21:23 UTC 2013 (97c14ba)
```

**Comment by Mailaender** [comment]
The check for wrong password however works so some kind of connection must still be possible.
