### ISSUE TITLE
Debugging is hard.

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#585]
Right now when running Desura under GDB, it's impossible to break in a file, break in GDB at runtime, catch crashes, or catch exceptions.

**Comment by karolherbst** [comment]
does it make any difference with this branch? https://github.com/karolherbst/Desurium/tree/breakpad

**Comment by karolherbst** [comment]
wxWidgets is quitting the application somewhere, I try to debug this.

**Comment by karolherbst** [comment]
mhh, I found out, that I have only problems in qtcreator. plain gdb from command line works fine oO
