### ISSUE TITLE
doesn't build with v8-3.19.18.19

### ISSUE THREAD

**Issue by hasufell** [desura/Desurium#591]
http://dev.gentoo.org/~hasufell/desurium-0.8.0_rc10:20130822-145234.log

**Comment by karolherbst** [comment]
already fixed in 0.8.0_rc11-dev and 0.9-dev

patch used by desurium-overlay: https://github.com/desura/desurium-overlay/blob/master/games-util/desurium/files/desurium-v8-3.19.18.patch
