### ISSUE TITLE
leveldb depdendency?

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#6]
When trying to build cef I get an exception about being unable to find leveldb's gyp file.

**Comment by lodle** [comment]
never had this before. Can you post the output of the error?

**Comment by Jookia** [comment]
It seems I was running it from the wrong folder. Gah.

**Comment by Jookia** [comment]
Actually, that broke it. It was because I had the wrong repo checked out for chromium. Fixed by Lodle.
