### ISSUE TITLE
Breakpad from zip: configure not executable

### ISSUE THREAD

**Issue by makson96** [desura/Desurium#608]
If you extract old breakpad archive (breakpad-850.tar.gz) and compare it to new one (breakpad-850-r1.zip) you will see that in zip archive "configure" file is not marked as executable. It may lead to compilation issues:
https://launchpadlibrarian.net/150345483/buildlog_ubuntu-raring-amd64.desurium_3%3A0.9.0~20130915-1ubuntu1makson1_FAILEDTOBUILD.txt.gz

```
[  0%] Performing patch-bug-158 step for 'breakpad'
=== creating patch backup to /build/buildd/desurium-0.9.0~20130915/build_dir/breakpad-prefix/src/breakpad/bak_bug-158.patch ===
patching file Makefile.in
patching file Makefile.am
=== fake patch step returns with 0 ===
=== test succeeded. Apply patch ===
patching file Makefile.in
patching file Makefile.am
=== backing up new patch file ===
[  0%] No update step for 'breakpad'
[  1%] No patch step for 'breakpad'
[  1%] Performing configure step for 'breakpad'
/bin/sh: 1: /build/buildd/desurium-0.9.0~20130915/build_dir/breakpad-prefix/src/breakpad/configure: Permission denied
make[3]: *** [breakpad-prefix/src/breakpad-stamp/breakpad-configure] Error 126
```

This is pretty trivial, but I am not sure if zip archive can event keep proper execution permissions. So either we make sure that cmake will mark this file as executable or we will switch back to tar.gz.

**Comment by karolherbst** [comment]
does this commit help? https://github.com/karolherbst/Desurium/commit/ce54d93a4ed5bd48300405b285d8eb0268608bce

**Comment by makson96** [comment]
Yes it does.
https://launchpad.net/~makson96/+archive/desurium/+build/5033551

**Comment by karolherbst** [comment]
great
