### ISSUE TITLE
bin dir gets changed after login causing scriptcore.dll to fail to load

### ISSUE THREAD

**Issue by lodle** [desura/Desurium#619]

**Comment by lodle** [comment]
Caused by wxWidgets (added a break point on SetDllDirectory) where it doesnt restore the dll directory properly

**Comment by lodle** [comment]
http://trac.wxwidgets.org/ticket/15534

**Comment by Jookia** [comment]
We might want to add this to our wxWidgets patches.

**Comment by lodle** [comment]
Already there jookia

**Comment by karolherbst** [comment]
Is this fixed with newer wxWidgets?

**Comment by karolherbst** [comment]
ahh, this is a new wxwidgets bug
