### ISSUE TITLE
Desura doesnt stay in ubuntu launch bar

### ISSUE THREAD

**Issue by lodle** [desura/Desurium#656]
http://www.moddb.com/groups/desura/forum/thread/launcher-on-ubuntu-1110/#692099

**Comment by makson96** [comment]
This is report from 2011. Are we sure the issue is present now?

**Comment by lodle** [comment]
Would be nice if some one who has Ubuntu checked

**Comment by makson96** [comment]
On Ubuntu 13.10 Desurium icon (launcher) stays on Unity launcher bar (vertical one on the left of the screen) after I logout and login back to the system.

**Comment by Jookia** [comment]
I'd attribute this to the process hanging.

**Comment by makson96** [comment]
It should stay on this bar. I wanted to say, that bug is unreproducible.
