### ISSUE TITLE
On Gentoo systems Desura segfaults when attempting to run twice

### ISSUE THREAD

**Issue by lodle** [desura/Desurium#657]

**Comment by karolherbst** [comment]
This never ever happend to me. Could you provde some more information here?

**Comment by lodle** [comment]
Thats all we had in trac. If tested and not an issue please close. Try running again while desura is open and then run again after you close desura.

**Comment by karolherbst** [comment]
We reworked the already running test over and over. I know that this is wxWidgets related and could be fixed a long time ago. Anyway we didn't get any bug report because of a non working running instance check.
