### ISSUE TITLE
Remove custom windows chrome causing many issues

### ISSUE THREAD

**Issue by lodle** [desura/Desurium#658]

**Comment by karolherbst** [comment]
Wich issues for example? I only noticed, that the windows looking very windows 7 like on a windows 8 machine, but nothing else.

**Comment by lodle** [comment]
We had around 10 issues on our internal bug tracker with quirks that windows did with normal windows and the desura windows didnt follow like drag to top of screen to fully maximize.

**Comment by karolherbst** [comment]
okay
