### ISSUE TITLE
Uninstall text

### ISSUE THREAD

**Issue by Protektor-Desura** [desura/Desurium#66]
When you go to uninstall a game right now the two checkboxes you see are:
Remove Desura Files
Remove From Account

The second one is not correct. A game can never be removed from an account once it is purchased or added. All it is doing is no longer displaying that game in the client. The text should be:

"Remove from Client Game List"  or  "Remove From Local Game List"
or something similar.

The only reason this exists is so that you can remove the shortcuts that you create to your own games that are not from Desura.

**Comment by ssokolow** [comment]
As far as I can tell, that second option actually does do what it says it does if the listed price is "FREE".

The effects of those checkboxes could definitely be made more clear though.

**Comment by Jookia** [comment]
I'll do this for the English translation, but all the other translations will need to be updated too.

**Comment by Jookia** [comment]
Fixed as of commit 26578700c4.
