### ISSUE TITLE
Curl - 7.21.5 

### ISSUE THREAD

**Issue by khaledzayed** [desura/Desurium#67]
I am using curl - 7.21.5 to issue HTTP requests to fetch data segments. Under bad channel conditions I will be forced to cancel the issued HTTP request. 

My Question: When I cancel a HTTP request do I receive 0 bytes? or do I receive a portion of the requested segment?

Example: I issued a HTTP request for 1 MB segment. After 3 seconds I decided to cancel the request. Do I receive a portion of the requested segment after cancellation or do I receive 0 bytes ?

**Comment by ssokolow** [comment]
This is an bug/feature tracker, not a Programming Q&A board. You should probably take your question to [StackOverflow.com](http://www.stackoverflow.com).

**Comment by khaledzayed** [comment]
Thanks for helping :)
