### ISSUE TITLE
Gentoo build fail

### ISSUE THREAD

**Issue by aljones15** [desura/Desurium#68]
/var/tmp/portage/games-util/desurium-0.999/temp/environment: line 2461: ./build.sh: No such file or directory 
make: **\* No targets specified and no makefile found. Stop. 
- ERROR: games-util/desurium-0.999 failed (compile phase): 
- (no error message) 
- 
- Call stack: 
- ebuild.sh, line 85: Called src_compile 
- environment, line 2462: Called die 
- The specific snippet of code: 
- make || die 
- 
- If you need support, post the output of 'emerge --info =games-util/desurium-0.999', 
- the complete build log and the output of 'emerge -pqv =games-util/desurium-0.999'. 
- This ebuild is from an overlay named 'AzP': '/var/lib/layman/AzP/' 
- The complete build log is located at '/var/tmp/portage/games-util/desurium-0.999/temp/build.log'. 
- The ebuild environment file is located at '/var/tmp/portage/games-util/desurium-0.999/temp/environment'. 
- S: '/var/tmp/portage/games-util/desurium-0.999/work/desurium' 

> > > Failed to emerge games-util/desurium-0.999, Log file: 
> > > 
> > > '/var/tmp/portage/games-util/desurium-0.999/temp/build.log' 
- Messages for package app-admin/eselect-wxwidgets-1.4: 
- By default the system wxWidgets profile is set to "none". 
- 
- It is unnecessary to change this unless you are doing development work 
- with wxGTK outside of portage. The package manager ignores the profile 
- setting altogether. 
- Messages for package dev-vcs/subversion-1.6.17-r7: 
- If you run subversion as a daemon, you will need to restart it to avoid module mismatches. 
- Messages for package games-util/desurium-0.999: 
- ERROR: games-util/desurium-0.999 failed (compile phase): 
- (no error message) 
- 
- Call stack: 
- ebuild.sh, line 85: Called src_compile 
- environment, line 2462: Called die 
- The specific snippet of code: 
- make || die 
- 
- If you need support, post the output of 'emerge --info =games-util/desurium-0.999', 
- the complete build log and the output of 'emerge -pqv =games-util/desurium-0.999'. 
- This ebuild is from an overlay named 'AzP': '/var/lib/layman/AzP/' 
- The complete build log is located at '/var/tmp/portage/games-util/desurium-0.999/temp/build.log'. 
- The ebuild environment file is located at '/var/tmp/portage/games-util/desurium-0.999/temp/environment'. 
- S: '/var/tmp/portage/games-util/desurium-0.999/work/desurium' 
- GNU info directory index is up-to-date. 

emerge --info =games-util/desurium-0.999 
# Portage 2.1.10.44 (default/linux/x86/10.0, gcc-4.5.3, glibc-2.12.2, 3.0.6-gentoo i686) 
# System Settings 

System uname: Linux-3.0.6-gentoo-i686-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.0.3 
Timestamp of tree: Fri, 10 Feb 2012 04:45:01 +0000 
app-shells/bash: 4.1_p9 
dev-java/java-config: 2.1.11-r3 
dev-lang/python: 2.7.2-r3, 3.1.4-r3 
dev-util/cmake: 2.8.6-r4 
dev-util/pkgconfig: 0.26 
sys-apps/baselayout: 2.0.3 
sys-apps/openrc: 0.8.3-r1 
sys-apps/sandbox: 2.4 
sys-devel/autoconf: 2.13, 2.68 
sys-devel/automake: 1.11.1 
sys-devel/binutils: 2.20.1-r1 
sys-devel/gcc: 4.5.3-r1 
sys-devel/gcc-config: 1.4.1-r1 
sys-devel/libtool: 2.4-r1 
sys-devel/make: 3.82-r1 
sys-kernel/linux-headers: 2.6.39 (virtual/os-headers) 
sys-libs/glibc: 2.12.2 
Repositories: gentoo AzP 
ACCEPT_KEYWORDS="x86" 
ACCEPT_LICENSE="\* -@EULA" 
CBUILD="i686-pc-linux-gnu" 
CFLAGS="-O2 -march=i686 -pipe" 
CHOST="i686-pc-linux-gnu" 
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt" 
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/env.d/java/ /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo" 
CXXFLAGS="-O2 -march=i686 -pipe" 
DISTDIR="/usr/portage/distfiles" 
FEATURES="assume-digests binpkg-logs distlocks ebuild-locks fixlafiles news parallel-fetch protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch" 
FFLAGS="" 
GENTOO_MIRRORS="http://gentoo.aditsu.net:8000/" 
LANG="C" 
LDFLAGS="-Wl,-O1 -Wl,--as-needed" 
PKGDIR="/usr/portage/packages" 
PORTAGE_CONFIGROOT="/" 
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --compress --force --whole-file --delete --stats --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages" 
PORTAGE_TMPDIR="/var/tmp" 
PORTDIR="/usr/portage" 
PORTDIR_OVERLAY="/var/lib/layman/AzP" 
SYNC="rsync://rsync.sg.gentoo.org/gentoo-portage" 
USE="X acl berkdb bzip2 cli cracklib crypt cups cxx dbus dri fortran gdbm gnome gpm gtk iconv ipv6 modules mudflap ncurses nls nptl nptlonly openmp pam pcre pppd readline session ssl sysfs tcpd unicode x86 xorg zlib" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1 emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" ALSA_PCM_PLUGINS="adpcm alaw asym copy dmix dshare dsnoop empty extplug file hooks iec958 ioplug ladspa lfloat linear meter mmap_emul mulaw multi null plug rate route share shm softvol" APACHE2_MODULES="actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan stage tables krita karbon braindump" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ubx" INPUT_DEVICES="evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" PHP_TARGETS="php5-3" RUBY_TARGETS="ruby18" USERLAND="GNU" VIDEO_CARDS="fbdev glint intel mach64 mga neomagic nouveau nv r128 radeon savage sis tdfx trident vesa via vmware dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account" 
Unset: CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, MAKEOPTS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS 

emerge -pqv =games-util/desurium-0.999 
[ebuild N ] games-util/desurium-0.999 

help?

**Comment by aljones15** [comment]
This is using the enuild from AzP the gentoo forums suggested I post here.

**Comment by yurikoles** [comment]
Did you try creating symlink /bin/sh to /bin/bash?

**Comment by aljones15** [comment]
it ended up being a couple of things
1st in gentoo the wxWidgets needs a profile in order to compile ebuilds from overlays
http://wiki.wxwidgets.org/Installing_and_configuring_under_Gentoo

Seconds I had to emerge apache so Subversion would work.
I had to restart subversion too:
http://en.gentoo-wiki.com/wiki/Subversion/Install

next I had to go into the tmp folder where the ebuild downloaded all the librarys find src/third_party and run ./BuildAll.sh by myself
then I had to go to lin_build and run ./build.sh but this gave errors from libs.gpy
so I went back to src/third_party and changed the libs.gyp file so that type settings was changed to none.
I had to do this for all the libraries.

**Comment by aljones15** [comment]
still getting this error:
./desura
./desura: error while loading shared libraries: libcares_desura.so.2: cannot open shared object file: No such file or directory
that's from the binary in 
out/Debug

from the binary in /build_out/debug_lin/desura
ebug_lin # ./desura
./desura: line 209: cd: ./lib_extra: No such file or directory
./desura: line 106: ../bin/findlib.sh: No such file or directory
ln: failed to create symbolic link `../lib/_.so_': No such file or directory
./desura: line 305: /root/Downloads/Desurium/build_out/bin/desura: No such file or directory
./desura: line 305: exec: /root/Downloads/Desurium/build_out/bin/desura: cannot execute: No such file or directory

and from the release_lin
release_lin # ./desura
./desura: line 209: cd: ./lib_extra: No such file or directory
./desura: line 106: ../bin/findlib.sh: No such file or directory
ln: failed to create symbolic link `../lib/_.so_': No such file or directory
./desura: line 305: /root/Downloads/Desurium/build_out/bin/desura: No such file or directory
./desura: line 305: exec: /root/Downloads/Desurium/build_out/bin/desura: cannot execute: No such file or directory

OH WAIT
test.sh does work... jesus... anyway looks like it's running ok.

**Comment by yurikoles** [comment]
It's an ebuild problem. Author explaianed this clearly on [gentoo forum](http://forums.gentoo.org/viewtopic-p-6971616.html#6971616)

**Comment by aljones15** [comment]
The later were errors from the copy I downloaded using got and compiled outside of the build. Also have compiled it successfully now.
