### ISSUE TITLE
Gef is included in the repo

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#7]
Considering we're suppose to symlink the gef folder to the chromium one, it doesn't seem that the src/third_party/gefs folder should be in this repo.

**Comment by lodle** [comment]
I think you mean cef and the reason its in the repo as i have made changes to chromium and cef and its just easier that way

**Comment by Jookia** [comment]
Ah. But the instructions say to "ln -s chromium/src/cef cef" which overwrites it?
Speaking of the instructions, it tells you to chmod +x stuff in cef. Shouldn't that already be done?

Gah, I skipped a step and that doesn't overwrite it. I'm silly.

**Comment by lodle** [comment]
need to move it to the root of the chromium/src dir as it needs to be built from there. Should all ready be chmod'ed
