### ISSUE TITLE
Kubuntu 12.04 crash 

### ISSUE THREAD

**Issue by yurikoles** [desura/Desurium#70]
muhlis@muhlis-ubuntu:~$ desura/desura 

Gtk-WARNING *_: /home/muhlis/desura/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/liboxygen-gtk.so)
*_\* glibc detected **\* bin/desura: munmap_chunk(): invalid pointer: 0x00007fbc6c0e4aa0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7c8b6)[0x7fbcb93858b6]
/home/muhlis/desura/lib/libusercore.so(+0xc76ad)[0x7fbcb5e4b6ad]
/home/muhlis/desura/lib/libusercore.so(+0x100446)[0x7fbcb5e84446]
/home/muhlis/desura/lib/libusercore.so(+0x100a4d)[0x7fbcb5e84a4d]
/home/muhlis/desura/lib/libusercore.so(+0x7134b)[0x7fbcb5df534b]
/home/muhlis/desura/lib/libusercore.so(+0xb63ee)[0x7fbcb5e3a3ee]
/home/muhlis/desura/lib/libusercore.so(+0xb7058)[0x7fbcb5e3b058]
/home/muhlis/desura/lib/libusercore.so(+0x1b4b8d)[0x7fbcb5f38b8d]
/home/muhlis/desura/lib/libboost_thread-desura.so.1.47.0(+0xf927)[0x7fbcb7ed3927]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a)[0x7fbcba325e9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fbcb93f974d]
======= Memory map: ========
00400000-0060a000 r-xp 00000000 08:08 14158687                           /home/muhlis/desura/bin/desura
00809000-00816000 rw-p 00209000 08:08 14158687                           /home/muhlis/desura/bin/desura
00816000-0082a000 rw-p 00000000 00:00 0 
02026000-0214f000 rw-p 00000000 00:00 0                                  [heap]
0214f000-03e4c000 rw-p 00000000 00:00 0                                  [heap]
7fbc23297000-7fbc23298000 ---p 00000000 00:00 0 
7fbc23298000-7fbc23a98000 rw-p 00000000 00:00 0 
7fbc23a98000-7fbc23a99000 ---p 00000000 00:00 0 
7fbc23a99000-7fbc24299000 rw-p 00000000 00:00 0 
7fbc24299000-7fbc2429a000 ---p 00000000 00:00 0 
7fbc2429a000-7fbc24a9a000 rw-p 00000000 00:00 0 
7fbc24a9a000-7fbc24a9b000 ---p 00000000 00:00 0 
7fbc24a9b000-7fbc2529b000 rw-p 00000000 00:00 0 
7fbc2529b000-7fbc2529c000 ---p 00000000 00:00 0 
7fbc2529c000-7fbc25a9c000 rw-p 00000000 00:00 0 
7fbc25a9c000-7fbc25a9d000 ---p 00000000 00:00 0 
7fbc25a9d000-7fbc2629d000 rw-p 00000000 00:00 0 
7fbc2629d000-7fbc2629e000 ---p 00000000 00:00 0 
7fbc2629e000-7fbc26a9e000 rw-p 00000000 00:00 0 
7fbc26a9e000-7fbc26a9f000 ---p 00000000 00:00 0 
7fbc26a9f000-7fbc2729f000 rw-p 00000000 00:00 0 
7fbc2729f000-7fbc272a0000 ---p 00000000 00:00 0 
7fbc272a0000-7fbc27aa0000 rw-p 00000000 00:00 0 
7fbc29aa4000-7fbc29ae4000 rw-p 00000000 00:00 0 
7fbc29ae4000-7fbc29ae5000 ---p 00000000 00:00 0 
7fbc29ae5000-7fbc2a2e5000 rw-p 00000000 00:00 0 
7fbc2a2e5000-7fbc2a2e6000 ---p 00000000 00:00 0 
7fbc2a2e6000-7fbc2aae6000 rw-p 00000000 00:00 0 
7fbc2aae6000-7fbc2aae7000 ---p 00000000 00:00 0 
7fbc2aae7000-7fbc2b4a7000 rw-p 00000000 00:00 0 
7fbc2bca8000-7fbc2bca9000 ---p 00000000 00:00 0 
7fbc2bca9000-7fbc2c4a9000 rw-p 00000000 00:00 0 
7fbc2c4a9000-7fbc2c4aa000 ---p 00000000 00:00 0 
7fbc2c4aa000-7fbc2ccaa000 rw-p 00000000 00:00 0 
7fbc2ccaa000-7fbc2ccab000 ---p 00000000 00:00 0 
7fbc2ccab000-7fbc2d4ab000 rw-p 00000000 00:00 0 
7fbc2d82c000-7fbc2dcac000 rw-p 00000000 00:00 0 
7fbc2fc30000-7fbc2fcb0000 rw-p 00000000 00:00 0 
7fbc304b1000-7fbc304f1000 rw-p 00000000 00:00 0 
7fbc304f2000-7fbc305b2000 rw-p 00000000 00:00 0 
7fbc305b6000-7fbc3063e000 rw-p 00000000 00:00 0 
7fbc30dbf000-7fbc31604000 rw-p 00000000 00:00 0 
7fbc31604000-7fbc31605000 r-xp 00000000 08:07 552121                     /usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so
7fbc31605000-7fbc31804000 ---p 00001000 08:07 552121                     /usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so
7fbc31804000-7fbc31805000 r--p 00000000 08:07 552121                     /usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so
7fbc31805000-7fbc31806000 rw-p 00001000 08:07 552121                     /usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so
7fbc31806000-7fbc3182b000 r-xp 00000000 08:07 543655                     /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0.1400.2
7fbc3182b000-7fbc31a2a000 ---p 00025000 08:07 543655                     /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0.1400.2
7fbc31a2a000-7fbc31a2b000 r--p 00024000 08:07 543655                     /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0.1400.2
7fbc31a2b000-7fbc31a2c000 rw-p 00025000 08:07 543655                     /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0.1400.2
7fbc31a2c000-7fbc31a2f000 r-xp 00000000 08:07 581666                     /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
7fbc31a2f000-7fbc31c2e000 ---p 00003000 08:07 581666                     /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
7fbc31c2e000-7fbc31c2f000 r--p 00002000 08:07 581666                     /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
7fbc31c2f000-7fbc31c30000 rw-p 00003000 08:07 581666                     /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
7fbc31c30000-7fbc31c33000 r-xp 00000000 08:07 526670                     /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
7fbc31c33000-7fbc31e32000 ---p 00003000 08:07 526670                     /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
7fbc31e32000-7fbc31e33000 r--p 00002000 08:07 526670                     /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
7fbc31e33000-7fbc31e34000 rw-p 00003000 08:07 526670                     /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
7fbc31e34000-7fbc31e4b000 r-xp 00000000 08:07 543411                     /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7fbc31e4b000-7fbc3204a000 ---p 00017000 08:07 543411                     /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7fbc3204a000-7fbc3204b000 r--p 00016000 08:07 543411                     /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7fbc3204b000-7fbc3204c000 rw-p 00017000 08:07 543411                     /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7fbc3204c000-7fbc32acd000 r-xp 00000000 08:07 543541                     /usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.0
7fbc32acd000-7fbc32ccd000 ---p 00a81000 08:07 543541                     /usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.0
7fbc32ccd000-7fbc32d0f000 r--p 00a81000 08:07 543541                     /usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.0
7fbc32d0f000-7fbc32d16000 rw-p 00ac3000 08:07 543541                     /usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.0
7fbc32d16000-7fbc32d1a000 rw-p 00000000 00:00 0 
7fbc32d1a000-7fbc32fdf000 r-xp 00000000 08:07 543486                     /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.0
7fbc32fdf000-7fbc331df000 ---p 002c5000 08:07 543486                     /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.0
7fbc331df000-7fbc331ea000 r--p 002c5000 08:07 543486                     /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.0

**Comment by Jookia** [comment]
Is this Desura or Desurium?

**Comment by yurikoles** [comment]
Desura

**Comment by Jookia** [comment]
Then we can't help.

**Comment by yurikoles** [comment]
I will try to reproduce on desurium
