### ISSUE TITLE
Failed to load cef library: 0

### ISSUE THREAD

**Issue by aljones15** [desura/Desurium#73]
actually have a new error, everything compiles now, but desurium shows up with a blank screen, this is the error:

04:30 MCFCore Logging Started.
04:30 WebCore Logging Started.
04:30 UserCore Logging Started.
04:30 --------------------------------------------------
04:30 Desura Version : 1.0.0.0
04:30 MCFCore Version : 0.0.0.1
04:30 UICore Version : 0.0.0.1
04:30 UserCore Version : 0.0.0.1
04:30 WebCore Version : 0.0.0.1
04:30 --------------------------------------------------
04:30 Logging Has started
04:30

04:30 DS: Version: 0.0.0.1
04:30 Failed to load cef library: 0
04:30 CEF_CreateCookie is NULL. Failed to set cookies. :(
04:30 wx Assert: ./src/gtk/bitmap.cpp(554): assert "IsOk()" failed in GetHeight(): invalid bitmap
04:30 Failed to load cef library: 0
04:30 Failed to load cef library: 0

Everything else works just fine, I can even play my games by using the tray icon.
I read that this error plagued Desura earlier because it used system libs instead of the libraries
that came with Desura.

Anyway, have been goolging, but all the solutions so far are to force an update which I don't think I can do with Desurium... or can I?

I also already tried installing orbit and libSDL and then recompiling.

**Comment by Jookia** [comment]
This is a I've had since the start: Building Cef doesn't work, at least on my system.

Just copy the Cef libs from the official Desura build for now.

**Comment by aljones15** [comment]
Will do.

thanks for your time.

Andrew

**Comment by Jookia** [comment]
I'm assigning myself to this instead of closing it, as a reminder to get Cef working.

**Comment by aljones15** [comment]
I copied libcef_desura.so from my normal desura install to the lib folders in Desurium/build_out/release_lin/lib and debug_lin/lib however I still get the error. You mentioned multiple cef libs in your comment. What else should I copy?

**Comment by Jookia** [comment]
I don't remember at the moment. Copy any that Desurium didn't build I guess?

**Comment by Gigadoc2** [comment]
'ldd build_out/debug_lin/lib/libcef_desura.so | grep "not found"' should show you a bunch of libraries. Look if you can find them in your Desurium 'build_out/debug_lin/lib/'-folder, and copy any libs missing from your old installation to that folder.

If this still doesn't work, try looking at the output in your terminal when launching Desurium, it should mention missing libs.

Had the same problem, but that solved it for me.

**Comment by aljones15** [comment]
yeah did it, copied them to the deub_lin/lib and it works now, but still getting a few errors. Notably: 

sert: ./src/gtk/bitmap.cpp(554): assert "IsOk()" failed in GetHeight(): invalid bitmap
15:20   Failed crc check. Writen to log file [/home/liminal/Downloads/Desurium/build_out/debug_lin/.settings/crc/crc_log.txt], block saved to file [/home/liminal/Downloads/Desurium/build_out/debug_lin/.settings/crc/24597277704224/block_528367_1330932049.bin].
15:20   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
15:20   Failed crc check. Writen to log file [/home/liminal/Downloads/Desurium/build_out/debug_lin/.settings/crc/crc_log.txt], block saved to file [/home/liminal/Downloads/Desurium/build_out/debug_lin/.settings/crc/24597277704224/block_120255990_1330932058.bin].
15:20   Mcf download thread errored out. Id: 1, Error: Crc of the download chunk didnt match what was expected [0]
15:21   Failed crc check. Writen to log file [/home/liminal/Downloads/Desurium/build_out/debug_lin/.settings/crc/crc_log.txt], block saved to file 

but again... IT WORKS!!!! ahhh native-ish desura on my gentoo machine =)

**Comment by Jookia** [comment]
I've never had that error. Sorry for not being of help.

**Comment by Protektor-Desura** [comment]
The failed CRC is nothing. I think it is just left over debug messages. If a block fails CRC during download it is re-downloaded. The whole game downloaded will be valid. The CRC errors just let you know that a block failed and it had to be requested again. This error message could be removed without it actually effecting the performance of the client.

**Comment by Jookia** [comment]
Irrelevant now.
