### ISSUE TITLE
install-deps and ArchLinux multilib

### ISSUE THREAD

**Issue by Gigadoc2** [desura/Desurium#74]
The script 'install-deps.sh' tries to install the regular packages 'binutils' and 'gcc' from the repo 'base', in order to be able compiling the source.

This is fine for users of the i686 builds of Arch, however some of the x86_64 arch users have installed the packages 'binutils-multilib' and 'gcc-multilib' from the 'multilib' repo, which might lead to a dependency conflict, since those packages are needed to build i686 software on x86_64 systems.

**Comment by Jookia** [comment]
We're not building any i686 software, or using multilib tools. I know this for a fact; I run Arch Linux x86_64, although without multilib support. I don't see the problem here.

**Comment by Gigadoc2** [comment]
The point is, multilib-packages conflict with the regular ones, since they are intended to replace them, exceeding the functionality of the regular tools (instead of being seperate tools for i686).

I have installed the multilib packages, and running install-deps, pacman wants to remove those packages, in order to install the regular versions. But AFAIK compiling with the multilib tools would work flawlessly, because they can also build native x86_64 software. I am building right now, and so far there are no complaints about gcc or binutils.

**Comment by Jookia** [comment]
Hmm. I suppose the simple way is to check if installing gcc would conflict with existing packages, using some kind of pacman flag. I just checked  the manual and couldn't find one.

**Comment by Gigadoc2** [comment]
The strange thing is, shouldn't 'gcc-multilib' for example provide 'gcc'?
I am asking this question in #archlinux.de on freenode right now,  maybe I can get some help there…

**Comment by Jookia** [comment]
From what I understand, gcc-multilib and gcc are separate packages, and gcc-multilib provides whatever gcc provides, yet isn't the same package.

**Comment by Gigadoc2** [comment]
I don't know if this is the best possible solution, but we could use the deptest-feature of pacman.
'pacman -T gcc' for example would let pacman check if there was anything installed what provides gcc. In our case, 'gcc-multilib' does so, and pacman simply doesn't return any output. If now no gcc was installed, the command would output 'gcc', since it is the best package for providing gcc.

So basically we could do a full dependency check by issuing 'pacman -T <dependencylist>' , and simply give the output to 'pacman -S', which would then only install the dependencies left - no reinstalls or conflicts with multilib.

**Comment by Jookia** [comment]
Thanks for this. Fixed!
