### ISSUE TITLE
Desura 64 (and 32) exits without warning on openSUSE 12.1 x86_64.

### ISSUE THREAD

**Issue by olavd** [desura/Desurium#76]
While downloading, verifying, and otherwise working on game files, the client will suddenly just exit without any warnings. It does work normally for other uses (120.21). Nothing interesting is fed back when using strace, so a debug build might be required here …

**Comment by Jookia** [comment]
Could you recreate this in Desurium? Is [this](http://github.com/lodle/Desurium/issues/33) related?

**Comment by olavd** [comment]
I need to build it first though … #33 seems to cover it all.

**Comment by Jookia** [comment]
Alright, thanks man. I'ma close it to prevent duplication.
