### ISSUE TITLE
Supercomputer cluster required to build

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#8]
Building Desura uses 128 processes and brings my computer to a screeching halt, apparently it's due to the huge amount of IO being used.

**Comment by naryl** [comment]
I confirm. iotop shows that most of them waste 99% in iowait.

**Comment by lodle** [comment]
was this building cef? As that normally is massive amount of io and not much i can do about it.

**Comment by Jookia** [comment]
No, it's Desura.

**Comment by lodle** [comment]
dont see why it should be different to any other software as it just uses gcc and the source code is really not that big.

**Comment by Jookia** [comment]
We don't see why either, but it still happens. Maybe it's a gyp thing?

**Comment by lodle** [comment]
Any way to profile io usage on linux?
