### ISSUE TITLE
Don't copy branding

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#81]
It's generally a good idea to not modify the source directory when building, and it will break the idea of out of source builds if you do so.

**Comment by lodle** [comment]
Suggestions on how to fix this then?

Does cmake have virtual paths?

**Comment by Jookia** [comment]
I don't think so.

**Comment by Jookia** [comment]
After talking in IRC, the best idea I can think of is to copy a branding folder to the build folder, then add it to the include path.

**Comment by Jookia** [comment]
Fixed in the CMake fork.

**Comment by lodle** [comment]
how close is the cmake fork to merge?

**Comment by Jookia** [comment]
It depends how long until it works on Windows.
