### ISSUE TITLE
Filter Games by Tag

### ISSUE THREAD

**Issue by dleslie** [desura/Desurium#82]
It would be rather helpful to be able to tag games and later filter our library via a set of matching tags.

For instance, the only way I can get a handle on the hundreds of Steam games I currently own is by managing them by category. It would be preferable if Desura could support a flexible tagging system, with multiple tags, and filtering by tags.

Much like Icculus' SteamTags application, but in the Library itself.

**Comment by Jookia** [comment]
Sounds nice.
