### ISSUE TITLE
Add the ability to link to shell scripts or .love files for local games

### ISSUE THREAD

**Issue by user870** [desura/Desurium#83]
I was trying to add  Mari0 to my library, but I couldn't link to the .love file. So I wrote launch_mari0.sh that just said 

love-hg mari0_1.2.love

which is the command to start the game. I made it executable, tested it and it works. But, I guess the Desura client only looks for certain file types and .sh isn't one of them because the "Add" button was grayed out.

**Comment by Telemaniaka** [comment]
You where probably missing `#!/bin/bash` or `#!/bin/sh` at the start of your script. In that case Desura doesn't recognize it as valid.

**Comment by xjoda** [comment]
Well, don't I feel dumb. That's exactly what I did.

**Comment by lodle** [comment]
Other wise its hard to know what the file is.
