### ISSUE TITLE
Cef uses an outdated gyp file

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#9]
If you grep 'src/third_party/cef/cef.gyp' you'll see that it requires 'leveldb', which doesn't exist in the Chromium source tree (anymore at least, I read somewhere that it was removed). It also requires other things that aren't there.

Thus it can't build.

**Comment by lodle** [comment]
did you check out the correct version of chromium? As only the matching svn version (that is outlined in the build readme) will work

**Comment by lodle** [comment]
This is my bad, updated the revision for windows but didnt do the same for linux. Will fix today
