### ISSUE TITLE
Couldn't compile

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#97]
Compile log: http://pastebin.com/mtShHG9F

curl log: http://pastebin.com/kGcafvcF

wxwidgets log: http://pastebin.com/vAfnKs5S

Ubuntu 12.04, all deps installed.

Terminal output;

---

 Building: boost (please wait) 
 Logfile: /home/liam/Downloads/lodle-Desurium-f7b812f/src/third_party/build_lin/boost.log
 Exit Status: 0 (SUCCESS)

---

 Building: breakpad (please wait) 
 Logfile: /home/liam/Downloads/lodle-Desurium-f7b812f/src/third_party/build_lin/breakpad.log
 Exit Status: 0 (SUCCESS)

---

 Building: curl (please wait) 
 Failed At: make curl shared
 Logfile: /home/liam/Downloads/lodle-Desurium-f7b812f/src/third_party/build_lin/curl.log
 Exit Status: 1 (FAILED)

---

 Building: v8 (please wait) 
 Logfile: /home/liam/Downloads/lodle-Desurium-f7b812f/src/third_party/build_lin/v8.log
 Exit Status: 0 (SUCCESS)

---

 Building: wxWidgets (please wait) 
 Failed At: make release
 Logfile: /home/liam/Downloads/lodle-Desurium-f7b812f/src/third_party/build_lin/wxWidgets.log
 Exit Status: 1 (FAILED)

---

 Summary:
    Boost:      Success
    Breakpad:   Success
    Curl:       Failed
    V8:     Success
    wx:     Failed

---

rm: cannot remove `../src/branding': Is a directory
ln: failed to create symbolic link`../src/branding/branding_default': File exists

**Comment by Jookia** [comment]
Please try and compile karolherbst's branch.

**Comment by LiamDawe** [comment]
Where would i find this? Branches only lists Master.

**Comment by Jookia** [comment]
I mean fork. Go to his fork.
